# SPDX-License-Identifier: GPL-2.0-only
# This file is part of Scapy
# See https://scapy.net/ for more information
# AUTO-GENERATED by scapy/tools/generate_its_asn1.py - DO NOT EDIT

# scapy.contrib.status = skip
"""
ETSI ITS ASN.1 packets (UPER): CAM, DENM, IVIM, SPATEM, MAPEM.
"""

from scapy.asn1.asn1 import ASN1_Codecs
from scapy.asn1fields import (
    ASN1F_BIT_STRING,
    ASN1F_BOOLEAN,
    ASN1F_CHOICE,
    ASN1F_ENUMERATED,
    ASN1F_FLAGS,
    ASN1F_IA5_STRING,
    ASN1F_INTEGER,
    ASN1F_NULL,
    ASN1F_NUMERIC_STRING,
    ASN1F_PACKET,
    ASN1F_SEQUENCE,
    ASN1F_SEQUENCE_OF,
    ASN1F_STRING,
    ASN1F_UTF8_STRING,
    ASN1F_DEFAULT,
    ASN1F_optional,
)
from scapy.asn1packet import ASN1_Packet

class ItsPduHeader(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("protocolVersion", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_INTEGER("messageID", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_INTEGER("stationID", 0, uper_min=0, uper_max=4294967295, oer_unsigned=True)
    )


class DeltaReferencePosition(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("deltaLatitude", 0, uper_min=-131071, uper_max=131072),
        ASN1F_INTEGER("deltaLongitude", 0, uper_min=-131071, uper_max=131072),
        ASN1F_INTEGER("deltaAltitude", 0, uper_min=-12700, uper_max=12800)
    )


class Altitude(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("altitudeValue", 0, uper_min=-100000, uper_max=800001),
        ASN1F_ENUMERATED("altitudeConfidence", 0, {0: 'alt-000-01', 1: 'alt-000-02', 2: 'alt-000-05', 3: 'alt-000-10', 4: 'alt-000-20', 5: 'alt-000-50', 6: 'alt-001-00', 7: 'alt-002-00', 8: 'alt-005-00', 9: 'alt-010-00', 10: 'alt-020-00', 11: 'alt-050-00', 12: 'alt-100-00', 13: 'alt-200-00', 14: 'outOfRange', 15: 'unavailable'})
    )


class PosConfidenceEllipse(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("semiMajorConfidence", 0, uper_min=0, uper_max=4095, oer_unsigned=True),
        ASN1F_INTEGER("semiMinorConfidence", 0, uper_min=0, uper_max=4095, oer_unsigned=True),
        ASN1F_INTEGER("semiMajorOrientation", 0, uper_min=0, uper_max=3601, oer_unsigned=True)
    )


class PathPoint(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("pathPosition", DeltaReferencePosition(), DeltaReferencePosition),
        ASN1F_optional(ASN1F_INTEGER("pathDeltaTime", None, uper_min=1, uper_max=65535, oer_unsigned=True))
    )


class PathHistory(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE_OF(
        "pathPoints", [], PathPoint, uper_min=0, uper_max=40
    )


class PtActivation(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("ptActivationType", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_STRING("ptActivationData", b'', uper_min=1, uper_max=20)
    )


class CauseCode(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("causeCode", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_INTEGER("subCauseCode", 0, uper_min=0, uper_max=255, oer_unsigned=True), uper_extensible=True
    )


class Curvature(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("curvatureValue", 0, uper_min=-1023, uper_max=1023),
        ASN1F_ENUMERATED("curvatureConfidence", 0, {0: 'onePerMeter-0-00002', 1: 'onePerMeter-0-0001', 2: 'onePerMeter-0-0005', 3: 'onePerMeter-0-002', 4: 'onePerMeter-0-01', 5: 'onePerMeter-0-1', 6: 'outOfRange', 7: 'unavailable'})
    )


class Heading(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("headingValue", 0, uper_min=0, uper_max=3601, oer_unsigned=True),
        ASN1F_INTEGER("headingConfidence", 1, uper_min=1, uper_max=127, oer_unsigned=True)
    )


class ClosedLanes(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_ENUMERATED("innerhardShoulderStatus", 0, {0: 'availableForStopping', 1: 'closed', 2: 'availableForDriving'})),
        ASN1F_optional(ASN1F_ENUMERATED("outerhardShoulderStatus", 0, {0: 'availableForStopping', 1: 'closed', 2: 'availableForDriving'})),
        ASN1F_optional(ASN1F_BIT_STRING("drivingLaneStatus", None, uper_min=1, uper_max=13)), uper_extensible=True
    )


class Speed(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("speedValue", 0, uper_min=0, uper_max=16383, oer_unsigned=True),
        ASN1F_INTEGER("speedConfidence", 1, uper_min=1, uper_max=127, oer_unsigned=True)
    )


class LongitudinalAcceleration(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("longitudinalAccelerationValue", 0, uper_min=-160, uper_max=161),
        ASN1F_INTEGER("longitudinalAccelerationConfidence", 0, uper_min=0, uper_max=102, oer_unsigned=True)
    )


class LateralAcceleration(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("lateralAccelerationValue", 0, uper_min=-160, uper_max=161),
        ASN1F_INTEGER("lateralAccelerationConfidence", 0, uper_min=0, uper_max=102, oer_unsigned=True)
    )


class VerticalAcceleration(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("verticalAccelerationValue", 0, uper_min=-160, uper_max=161),
        ASN1F_INTEGER("verticalAccelerationConfidence", 0, uper_min=0, uper_max=102, oer_unsigned=True)
    )


class DangerousGoodsExtended(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_ENUMERATED("dangerousGoodsType", 0, {0: 'explosives1', 1: 'explosives2', 2: 'explosives3', 3: 'explosives4', 4: 'explosives5', 5: 'explosives6', 6: 'flammableGases', 7: 'nonFlammableGases', 8: 'toxicGases', 9: 'flammableLiquids', 10: 'flammableSolids', 11: 'substancesLiableToSpontaneousCombustion', 12: 'substancesEmittingFlammableGasesUponContactWithWater', 13: 'oxidizingSubstances', 14: 'organicPeroxides', 15: 'toxicSubstances', 16: 'infectiousSubstances', 17: 'radioactiveMaterial', 18: 'corrosiveSubstances', 19: 'miscellaneousDangerousSubstances'}),
        ASN1F_INTEGER("unNumber", 0, uper_min=0, uper_max=9999, oer_unsigned=True),
        ASN1F_BOOLEAN("elevatedTemperature", False),
        ASN1F_BOOLEAN("tunnelsRestricted", False),
        ASN1F_BOOLEAN("limitedQuantity", False),
        ASN1F_optional(ASN1F_IA5_STRING("emergencyActionCode", None, uper_min=1, uper_max=24)),
        ASN1F_optional(ASN1F_NUMERIC_STRING("phoneNumber", None, uper_min=1, uper_max=16)),
        ASN1F_optional(ASN1F_UTF8_STRING("companyName", None, uper_min=1, uper_max=24)), uper_extensible=True
    )


class VehicleIdentification(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_IA5_STRING("wMInumber", None, uper_min=1, uper_max=3)),
        ASN1F_optional(ASN1F_IA5_STRING("vDS", None, size_len=6)), uper_extensible=True
    )


class VehicleLength(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("vehicleLengthValue", 1, uper_min=1, uper_max=1023, oer_unsigned=True),
        ASN1F_ENUMERATED("vehicleLengthConfidenceIndication", 0, {0: 'noTrailerPresent', 1: 'trailerPresentWithKnownLength', 2: 'trailerPresentWithUnknownLength', 3: 'trailerPresenceIsUnknown', 4: 'unavailable'})
    )


class SteeringWheelAngle(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("steeringWheelAngleValue", 0, uper_min=-511, uper_max=512),
        ASN1F_INTEGER("steeringWheelAngleConfidence", 1, uper_min=1, uper_max=127, oer_unsigned=True)
    )


class YawRate(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("yawRateValue", 0, uper_min=-32766, uper_max=32767),
        ASN1F_ENUMERATED("yawRateConfidence", 0, {0: 'degSec-000-01', 1: 'degSec-000-05', 2: 'degSec-000-10', 3: 'degSec-001-00', 4: 'degSec-005-00', 5: 'degSec-010-00', 6: 'degSec-100-00', 7: 'outOfRange', 8: 'unavailable'})
    )


class ActionID(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("originatingStationID", 0, uper_min=0, uper_max=4294967295, oer_unsigned=True),
        ASN1F_INTEGER("sequenceNumber", 0, uper_min=0, uper_max=65535, oer_unsigned=True)
    )


class ProtectedCommunicationZone(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_ENUMERATED("protectedZoneType", 0, {0: 'permanentCenDsrcTolling', 1: 'temporaryCenDsrcTolling'}),
        ASN1F_optional(ASN1F_INTEGER("expiryTime", None, uper_min=0, uper_max=4398046511103, oer_unsigned=True)),
        ASN1F_INTEGER("protectedZoneLatitude", 0, uper_min=-900000000, uper_max=900000001),
        ASN1F_INTEGER("protectedZoneLongitude", 0, uper_min=-1800000000, uper_max=1800000001),
        ASN1F_optional(ASN1F_INTEGER("protectedZoneRadius", None, uper_min=1, uper_max=255, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("protectedZoneID", None, uper_min=0, uper_max=134217727, oer_unsigned=True)), uper_extensible=True
    )


class EventPoint(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("eventPosition", DeltaReferencePosition(), DeltaReferencePosition),
        ASN1F_optional(ASN1F_INTEGER("eventDeltaTime", None, uper_min=1, uper_max=65535, oer_unsigned=True, uper_extensible=True)),
        ASN1F_INTEGER("informationQuality", 0, uper_min=0, uper_max=7, oer_unsigned=True)
    )


class CenDsrcTollingZone(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("protectedZoneLatitude", 0, uper_min=-900000000, uper_max=900000001),
        ASN1F_INTEGER("protectedZoneLongitude", 0, uper_min=-1800000000, uper_max=1800000001),
        ASN1F_optional(ASN1F_INTEGER("cenDsrcTollingZoneID", None, uper_min=0, uper_max=134217727, oer_unsigned=True)), uper_extensible=True
    )


class BasicVehicleContainerHighFrequency(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("heading", Heading(), Heading),
        ASN1F_PACKET("speed", Speed(), Speed),
        ASN1F_ENUMERATED("driveDirection", 0, {0: 'forward', 1: 'backward', 2: 'unavailable'}),
        ASN1F_PACKET("vehicleLength", VehicleLength(), VehicleLength),
        ASN1F_INTEGER("vehicleWidth", 1, uper_min=1, uper_max=62, oer_unsigned=True),
        ASN1F_PACKET("longitudinalAcceleration", LongitudinalAcceleration(), LongitudinalAcceleration),
        ASN1F_PACKET("curvature", Curvature(), Curvature),
        ASN1F_ENUMERATED("curvatureCalculationMode", 0, {0: 'yawRateUsed', 1: 'yawRateNotUsed', 2: 'unavailable'}),
        ASN1F_PACKET("yawRate", YawRate(), YawRate),
        ASN1F_optional(ASN1F_FLAGS("accelerationControl", None, ['brakePedalEngaged', 'gasPedalEngaged', 'emergencyBrakeEngaged', 'collisionWarningEngaged', 'accEngaged', 'cruiseControlEngaged', 'speedLimiterEngaged'], uper_min=7, uper_max=7)),
        ASN1F_optional(ASN1F_INTEGER("lanePosition", None, uper_min=-1, uper_max=14)),
        ASN1F_optional(ASN1F_PACKET("steeringWheelAngle", None, SteeringWheelAngle)),
        ASN1F_optional(ASN1F_PACKET("lateralAcceleration", None, LateralAcceleration)),
        ASN1F_optional(ASN1F_PACKET("verticalAcceleration", None, VerticalAcceleration)),
        ASN1F_optional(ASN1F_INTEGER("performanceClass", None, uper_min=0, uper_max=7, oer_unsigned=True)),
        ASN1F_optional(ASN1F_PACKET("cenDsrcTollingZone", None, CenDsrcTollingZone))
    )


class BasicVehicleContainerLowFrequency(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_ENUMERATED("vehicleRole", 0, {0: 'default', 1: 'publicTransport', 2: 'specialTransport', 3: 'dangerousGoods', 4: 'roadWork', 5: 'rescue', 6: 'emergency', 7: 'safetyCar', 8: 'agriculture', 9: 'commercial', 10: 'military', 11: 'roadOperator', 12: 'taxi', 13: 'reserved1', 14: 'reserved2', 15: 'reserved3'}),
        ASN1F_FLAGS("exteriorLights", b'', ['lowBeamHeadlightsOn', 'highBeamHeadlightsOn', 'leftTurnSignalOn', 'rightTurnSignalOn', 'daytimeRunningLightsOn', 'reverseLightOn', 'fogLightOn', 'parkingLightsOn'], uper_min=8, uper_max=8),
        ASN1F_SEQUENCE_OF("pathHistory", [], PathPoint, uper_min=0, uper_max=40)
    )


class PublicTransportContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_BOOLEAN("embarkationStatus", False),
        ASN1F_optional(ASN1F_PACKET("ptActivation", None, PtActivation))
    )


class SpecialTransportContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_FLAGS("specialTransportType", b'', ['heavyLoad', 'excessWidth', 'excessLength', 'excessHeight'], uper_min=4, uper_max=4),
        ASN1F_FLAGS("lightBarSirenInUse", b'', ['lightBarActivated', 'sirenActivated'], uper_min=2, uper_max=2)
    )


class DangerousGoodsContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_ENUMERATED("dangerousGoodsBasic", 0, {0: 'explosives1', 1: 'explosives2', 2: 'explosives3', 3: 'explosives4', 4: 'explosives5', 5: 'explosives6', 6: 'flammableGases', 7: 'nonFlammableGases', 8: 'toxicGases', 9: 'flammableLiquids', 10: 'flammableSolids', 11: 'substancesLiableToSpontaneousCombustion', 12: 'substancesEmittingFlammableGasesUponContactWithWater', 13: 'oxidizingSubstances', 14: 'organicPeroxides', 15: 'toxicSubstances', 16: 'infectiousSubstances', 17: 'radioactiveMaterial', 18: 'corrosiveSubstances', 19: 'miscellaneousDangerousSubstances'})
    )


class RoadWorksContainerBasic(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_INTEGER("roadworksSubCauseCode", None, uper_min=0, uper_max=255, oer_unsigned=True)),
        ASN1F_FLAGS("lightBarSirenInUse", b'', ['lightBarActivated', 'sirenActivated'], uper_min=2, uper_max=2),
        ASN1F_optional(ASN1F_PACKET("closedLanes", None, ClosedLanes))
    )


class RescueContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_FLAGS("lightBarSirenInUse", b'', ['lightBarActivated', 'sirenActivated'], uper_min=2, uper_max=2)
    )


class EmergencyContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_FLAGS("lightBarSirenInUse", b'', ['lightBarActivated', 'sirenActivated'], uper_min=2, uper_max=2),
        ASN1F_optional(ASN1F_PACKET("incidentIndication", None, CauseCode)),
        ASN1F_optional(ASN1F_FLAGS("emergencyPriority", None, ['requestForRightOfWay', 'requestForFreeCrossingAtATrafficLight'], uper_min=2, uper_max=2))
    )


class SafetyCarContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_FLAGS("lightBarSirenInUse", b'', ['lightBarActivated', 'sirenActivated'], uper_min=2, uper_max=2),
        ASN1F_optional(ASN1F_PACKET("incidentIndication", None, CauseCode)),
        ASN1F_optional(ASN1F_ENUMERATED("trafficRule", 0, {0: 'noPassing', 1: 'noPassingForTrucks', 2: 'passToRight', 3: 'passToLeft'})),
        ASN1F_optional(ASN1F_INTEGER("speedLimit", None, uper_min=1, uper_max=255, oer_unsigned=True))
    )


class RSUContainerHighFrequency(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_SEQUENCE_OF("protectedCommunicationZonesRSU", None, ProtectedCommunicationZone, uper_min=1, uper_max=16)), uper_extensible=True
    )


class SituationContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("informationQuality", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_PACKET("eventType", CauseCode(), CauseCode),
        ASN1F_optional(ASN1F_PACKET("linkedCause", None, CauseCode)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("eventHistory", None, EventPoint, uper_min=1, uper_max=23)), uper_extensible=True
    )


class LocationContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_PACKET("eventSpeed", None, Speed)),
        ASN1F_optional(ASN1F_PACKET("eventPositionHeading", None, Heading)),
        ASN1F_SEQUENCE_OF("traces", [], PathHistory, uper_min=1, uper_max=7),
        ASN1F_optional(ASN1F_ENUMERATED("roadType", None, {0: 'urban-NoStructuralSeparationToOppositeLanes', 1: 'urban-WithStructuralSeparationToOppositeLanes', 2: 'nonUrban-NoStructuralSeparationToOppositeLanes', 3: 'nonUrban-WithStructuralSeparationToOppositeLanes'})), uper_extensible=True
    )


class ImpactReductionContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("heightLonCarrLeft", 1, uper_min=1, uper_max=100, oer_unsigned=True),
        ASN1F_INTEGER("heightLonCarrRight", 1, uper_min=1, uper_max=100, oer_unsigned=True),
        ASN1F_INTEGER("posLonCarrLeft", 1, uper_min=1, uper_max=127, oer_unsigned=True),
        ASN1F_INTEGER("posLonCarrRight", 1, uper_min=1, uper_max=127, oer_unsigned=True),
        ASN1F_SEQUENCE_OF("positionOfPillars", [], ASN1F_INTEGER, uper_min=1, uper_max=3, uper_extensible=True),
        ASN1F_INTEGER("posCentMass", 1, uper_min=1, uper_max=63, oer_unsigned=True),
        ASN1F_INTEGER("wheelBaseVehicle", 1, uper_min=1, uper_max=127, oer_unsigned=True),
        ASN1F_INTEGER("turningRadius", 1, uper_min=1, uper_max=255, oer_unsigned=True),
        ASN1F_INTEGER("posFrontAx", 1, uper_min=1, uper_max=20, oer_unsigned=True),
        ASN1F_FLAGS("positionOfOccupants", b'', ['row1LeftOccupied', 'row1RightOccupied', 'row1MidOccupied', 'row1NotDetectable', 'row1NotPresent', 'row2LeftOccupied', 'row2RightOccupied', 'row2MidOccupied', 'row2NotDetectable', 'row2NotPresent', 'row3LeftOccupied', 'row3RightOccupied', 'row3MidOccupied', 'row3NotDetectable', 'row3NotPresent', 'row4LeftOccupied', 'row4RightOccupied', 'row4MidOccupied', 'row4NotDetectable', 'row4NotPresent'], uper_min=20, uper_max=20),
        ASN1F_INTEGER("vehicleMass", 1, uper_min=1, uper_max=1024, oer_unsigned=True),
        ASN1F_ENUMERATED("requestResponseIndication", 0, {0: 'request', 1: 'response'})
    )


class StationaryVehicleContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_ENUMERATED("stationarySince", 0, {0: 'lessThan1Minute', 1: 'lessThan2Minutes', 2: 'lessThan15Minutes', 3: 'equalOrGreater15Minutes'})),
        ASN1F_optional(ASN1F_PACKET("stationaryCause", None, CauseCode)),
        ASN1F_optional(ASN1F_PACKET("carryingDangerousGoods", None, DangerousGoodsExtended)),
        ASN1F_optional(ASN1F_INTEGER("numberOfOccupants", None, uper_min=0, uper_max=127, oer_unsigned=True)),
        ASN1F_optional(ASN1F_PACKET("vehicleIdentification", None, VehicleIdentification)),
        ASN1F_optional(ASN1F_FLAGS("energyStorageType", None, ['hydrogenStorage', 'electricEnergyStorage', 'liquidPropaneGas', 'compressedNaturalGas', 'diesel', 'gasoline', 'ammonia'], uper_min=7, uper_max=7))
    )


class EuVehicleCategoryCode(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_ENUMERATED("euVehicleCategoryL", 0, {0: 'l1', 1: 'l2', 2: 'l3', 3: 'l4', 4: 'l5', 5: 'l6', 6: 'l7'}),
        ASN1F_ENUMERATED("euVehicleCategoryM", 0, {0: 'm1', 1: 'm2', 2: 'm3'}),
        ASN1F_ENUMERATED("euVehicleCategoryN", 0, {0: 'n1', 1: 'n2', 2: 'n3'}),
        ASN1F_ENUMERATED("euVehicleCategoryO", 0, {0: 'o1', 1: 'o2', 2: 'o3', 3: 'o4'}),
        ASN1F_NULL("euVehilcleCategoryT", None),
        ASN1F_NULL("euVehilcleCategoryG", None)
    )


class InternationalSign_speedLimits(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_INTEGER("speedLimitMax", None, uper_min=0, uper_max=250, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("speedLimitMin", None, uper_min=0, uper_max=250, oer_unsigned=True)),
        ASN1F_INTEGER("unit", 0, uper_min=0, uper_max=15, oer_unsigned=True)
    )


class DestinationRoad(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("derType", 0, uper_min=0, uper_max=15, oer_unsigned=True),
        ASN1F_optional(ASN1F_INTEGER("roadNumberIdentifier", None, uper_min=1, uper_max=999, oer_unsigned=True)),
        ASN1F_optional(ASN1F_UTF8_STRING("roadNumberText", None))
    )


class Distance(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("value", 1, uper_min=1, uper_max=16384, oer_unsigned=True),
        ASN1F_INTEGER("unit", 0, uper_min=0, uper_max=15, oer_unsigned=True)
    )


class DistanceOrDuration(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("value", 1, uper_min=1, uper_max=16384, oer_unsigned=True),
        ASN1F_INTEGER("unit", 0, uper_min=0, uper_max=15, oer_unsigned=True)
    )


class HoursMinutes(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("hours", 0, uper_min=0, uper_max=23, oer_unsigned=True),
        ASN1F_INTEGER("mins", 0, uper_min=0, uper_max=59, oer_unsigned=True)
    )


class MonthDay(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("month", 1, uper_min=1, uper_max=12, oer_unsigned=True),
        ASN1F_INTEGER("day", 1, uper_min=1, uper_max=31, oer_unsigned=True)
    )


class Weight(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("value", 1, uper_min=1, uper_max=16384, oer_unsigned=True),
        ASN1F_INTEGER("unit", 0, uper_min=0, uper_max=15, oer_unsigned=True)
    )


class ITS_Inline_InternationalSign_applicablePeriod_year(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("yearRangeStartYear", 2000, uper_min=2000, uper_max=2127, oer_unsigned=True),
        ASN1F_INTEGER("yearRangeEndYear", 2000, uper_min=2000, uper_max=2127, oer_unsigned=True)
    )


class ITS_Inline_InternationalSign_applicablePeriod_month_day(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("dateRangeStartMonthDay", MonthDay(), MonthDay),
        ASN1F_PACKET("dateRangeEndMonthDay", MonthDay(), MonthDay)
    )


class ITS_Inline_InternationalSign_applicablePeriod_hourMinutes(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("timeRangeStartTime", HoursMinutes(), HoursMinutes),
        ASN1F_PACKET("timeRangeEndTime", HoursMinutes(), HoursMinutes)
    )


class ITS_Inline_ITS_Inline_GddStructure_pictogramCode_serviceCategoryCode(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_ENUMERATED("trafficSignPictogram", 0, {0: 'dangerWarning', 1: 'regulatory', 2: 'informative'}),
        ASN1F_ENUMERATED("publicFacilitiesPictogram", 0, {0: 'publicFacilities'}),
        ASN1F_ENUMERATED("ambientOrRoadConditionPictogram", 0, {0: 'ambientCondition', 1: 'roadCondition'}), uper_extensible=True
    )


class ITS_Inline_ITS_Inline_GddStructure_pictogramCode_pictogramCategoryCode(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("nature", 1, uper_min=1, uper_max=9, oer_unsigned=True),
        ASN1F_INTEGER("serialNumber", 0, uper_min=0, uper_max=99, oer_unsigned=True)
    )


class AxleWeightLimits(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("maxLadenweightOnAxle1", 0, uper_min=0, uper_max=65535, oer_unsigned=True),
        ASN1F_INTEGER("maxLadenweightOnAxle2", 0, uper_min=0, uper_max=65535, oer_unsigned=True),
        ASN1F_INTEGER("maxLadenweightOnAxle3", 0, uper_min=0, uper_max=65535, oer_unsigned=True),
        ASN1F_INTEGER("maxLadenweightOnAxle4", 0, uper_min=0, uper_max=65535, oer_unsigned=True),
        ASN1F_INTEGER("maxLadenweightOnAxle5", 0, uper_min=0, uper_max=65535, oer_unsigned=True)
    )


class EnvironmentalCharacteristics(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_ENUMERATED("euroValue", 0, {0: 'noEntry', 1: 'euro-1', 2: 'euro-2', 3: 'euro-3', 4: 'euro-4', 5: 'euro-5', 6: 'euro-6', 7: 'reservedForUse1', 8: 'reservedForUse2', 9: 'reservedForUse3', 10: 'reservedForUse4', 11: 'reservedForUse5', 12: 'reservedForUse6', 13: 'reservedForUse7', 14: 'reservedForUse8', 15: 'eev'}),
        ASN1F_ENUMERATED("copValue", 0, {0: 'noEntry', 1: 'co2class1', 2: 'co2class2', 3: 'co2class3', 4: 'co2class4', 5: 'co2class5', 6: 'co2class6', 7: 'co2class7', 8: 'reservedforUse'})
    )


class ExhaustEmissionValues(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_ENUMERATED("unitType", 0, {0: 'mg-km', 1: 'mg-kWh'}),
        ASN1F_INTEGER("emissionCO", 0, uper_min=0, uper_max=32767, oer_unsigned=True),
        ASN1F_INTEGER("emissionHC", 0, uper_min=0, uper_max=65535, oer_unsigned=True),
        ASN1F_INTEGER("emissionNOX", 0, uper_min=0, uper_max=65535, oer_unsigned=True),
        ASN1F_INTEGER("emissionHCNOX", 0, uper_min=0, uper_max=65535, oer_unsigned=True)
    )


class PassengerCapacity(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("numberOfSeats", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_INTEGER("numberOfStandingPlaces", 0, uper_min=0, uper_max=255, oer_unsigned=True)
    )


class Provider(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_BIT_STRING("countryCode", b'', uper_min=10, uper_max=10),
        ASN1F_INTEGER("providerIdentifier", 0, uper_min=0, uper_max=16383, oer_unsigned=True)
    )


class SoundLevel(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("soundstationary", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_INTEGER("sounddriveby", 0, uper_min=0, uper_max=255, oer_unsigned=True)
    )


class VehicleDimensions(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("vehicleLengthOverall", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_INTEGER("vehicleHeigthOverall", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_INTEGER("vehicleWidthOverall", 0, uper_min=0, uper_max=255, oer_unsigned=True)
    )


class VehicleWeightLimits(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("vehicleMaxLadenWeight", 0, uper_min=0, uper_max=65535, oer_unsigned=True),
        ASN1F_INTEGER("vehicleTrainMaximumWeight", 0, uper_min=0, uper_max=65535, oer_unsigned=True),
        ASN1F_INTEGER("vehicleWeightUnladen", 0, uper_min=0, uper_max=65535, oer_unsigned=True)
    )


class ITS_Inline_DieselEmissionValues_particulate(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_ENUMERATED("unitType", 0, {0: 'mg-km', 1: 'mg-kWh'}),
        ASN1F_INTEGER("value", 0, uper_min=0, uper_max=32767, oer_unsigned=True)
    )


class AdvisorySpeed(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_ENUMERATED("type", 0, {0: 'none', 1: 'greenwave', 2: 'ecoDrive', 3: 'transit'}),
        ASN1F_optional(ASN1F_INTEGER("speed", None, uper_min=0, uper_max=500, oer_unsigned=True)),
        ASN1F_optional(ASN1F_ENUMERATED("confidence", 0, {0: 'unavailable', 1: 'prec100ms', 2: 'prec10ms', 3: 'prec5ms', 4: 'prec1ms', 5: 'prec0-1ms', 6: 'prec0-05ms', 7: 'prec0-01ms'})),
        ASN1F_optional(ASN1F_INTEGER("distance", None, uper_min=0, uper_max=10000, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("class_", None, uper_min=0, uper_max=255, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class ConnectingLane(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("lane", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_optional(ASN1F_FLAGS("maneuver", None, ['maneuverStraightAllowed', 'maneuverLeftAllowed', 'maneuverRightAllowed', 'maneuverUTurnAllowed', 'maneuverLeftTurnOnRedAllowed', 'maneuverRightTurnOnRedAllowed', 'maneuverLaneChangeAllowed', 'maneuverNoStoppingAllowed', 'yieldAllwaysRequired', 'goWithHalt', 'caution', 'reserved1'], uper_min=12, uper_max=12))
    )


class ConnectionManeuverAssist(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("connectionID", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_optional(ASN1F_INTEGER("queueLength", None, uper_min=0, uper_max=10000, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("availableStorageLength", None, uper_min=0, uper_max=10000, oer_unsigned=True)),
        ASN1F_optional(ASN1F_BOOLEAN("waitOnStop", None)),
        ASN1F_optional(ASN1F_BOOLEAN("pedBicycleDetect", None)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class DataParameters(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_IA5_STRING("processMethod", None, uper_min=1, uper_max=255)),
        ASN1F_optional(ASN1F_IA5_STRING("processAgency", None, uper_min=1, uper_max=255)),
        ASN1F_optional(ASN1F_IA5_STRING("lastCheckedDate", None, uper_min=1, uper_max=255)),
        ASN1F_optional(ASN1F_IA5_STRING("geoidUsed", None, uper_min=1, uper_max=255)), uper_extensible=True
    )


class IntersectionReferenceID(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_INTEGER("region", None, uper_min=0, uper_max=65535, oer_unsigned=True)),
        ASN1F_INTEGER("id", 0, uper_min=0, uper_max=65535, oer_unsigned=True)
    )


class LaneTypeAttributes(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_FLAGS("vehicle", b'', ['isVehicleRevocableLane', 'isVehicleFlyOverLane', 'hovLaneUseOnly', 'restrictedToBusUse', 'restrictedToTaxiUse', 'restrictedFromPublicUse', 'hasIRbeaconCoverage', 'permissionOnRequest'], uper_min=8, uper_max=8),
        ASN1F_FLAGS("crosswalk", b'', ['crosswalkRevocableLane', 'bicyleUseAllowed', 'isXwalkFlyOverLane', 'fixedCycleTime', 'biDirectionalCycleTimes', 'hasPushToWalkButton', 'audioSupport', 'rfSignalRequestPresent', 'unsignalizedSegmentsPresent'], uper_min=16, uper_max=16),
        ASN1F_FLAGS("bikeLane", b'', ['bikeRevocableLane', 'pedestrianUseAllowed', 'isBikeFlyOverLane', 'fixedCycleTime', 'biDirectionalCycleTimes', 'isolatedByBarrier', 'unsignalizedSegmentsPresent'], uper_min=16, uper_max=16),
        ASN1F_FLAGS("sidewalk", b'', ['sidewalk-RevocableLane', 'bicyleUseAllowed', 'isSidewalkFlyOverLane', 'walkBikes'], uper_min=16, uper_max=16),
        ASN1F_FLAGS("median", b'', ['median-RevocableLane', 'median', 'whiteLineHashing', 'stripedLines', 'doubleStripedLines', 'trafficCones', 'constructionBarrier', 'trafficChannels', 'lowCurbs', 'highCurbs'], uper_min=16, uper_max=16),
        ASN1F_FLAGS("striping", b'', ['stripeToConnectingLanesRevocableLane', 'stripeDrawOnLeft', 'stripeDrawOnRight', 'stripeToConnectingLanesLeft', 'stripeToConnectingLanesRight', 'stripeToConnectingLanesAhead'], uper_min=16, uper_max=16),
        ASN1F_FLAGS("trackedVehicle", b'', ['spec-RevocableLane', 'spec-commuterRailRoadTrack', 'spec-lightRailRoadTrack', 'spec-heavyRailRoadTrack', 'spec-otherRailType'], uper_min=16, uper_max=16),
        ASN1F_FLAGS("parking", b'', ['parkingRevocableLane', 'parallelParkingInUse', 'headInParkingInUse', 'doNotParkZone', 'parkingForBusUse', 'parkingForTaxiUse', 'noPublicParkingUse'], uper_min=16, uper_max=16), uper_extensible=True
    )


class Node_LLmD_64b(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("lon", 0, uper_min=-1800000000, uper_max=1800000001),
        ASN1F_INTEGER("lat", 0, uper_min=-900000000, uper_max=900000001)
    )


class Node_XY_20b(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("x", 0, uper_min=-512, uper_max=511),
        ASN1F_INTEGER("y", 0, uper_min=-512, uper_max=511)
    )


class Node_XY_22b(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("x", 0, uper_min=-1024, uper_max=1023),
        ASN1F_INTEGER("y", 0, uper_min=-1024, uper_max=1023)
    )


class Node_XY_24b(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("x", 0, uper_min=-2048, uper_max=2047),
        ASN1F_INTEGER("y", 0, uper_min=-2048, uper_max=2047)
    )


class Node_XY_26b(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("x", 0, uper_min=-4096, uper_max=4095),
        ASN1F_INTEGER("y", 0, uper_min=-4096, uper_max=4095)
    )


class Node_XY_28b(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("x", 0, uper_min=-8192, uper_max=8191),
        ASN1F_INTEGER("y", 0, uper_min=-8192, uper_max=8191)
    )


class Node_XY_32b(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("x", 0, uper_min=-32768, uper_max=32767),
        ASN1F_INTEGER("y", 0, uper_min=-32768, uper_max=32767)
    )


class NodeOffsetPointXY(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", Node_XY_20b(),
        Node_XY_20b,
        Node_XY_22b,
        Node_XY_24b,
        Node_XY_26b,
        Node_XY_28b,
        Node_XY_32b,
        Node_LLmD_64b
    )


class Position3D(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("lat", 0, uper_min=-900000000, uper_max=900000001),
        ASN1F_INTEGER("long", 0, uper_min=-1800000000, uper_max=1800000001),
        ASN1F_optional(ASN1F_INTEGER("elevation", None, uper_min=-4096, uper_max=61439)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class RegulatorySpeedLimit(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_ENUMERATED("type", 0, {0: 'unknown', 1: 'maxSpeedInSchoolZone', 2: 'maxSpeedInSchoolZoneWhenChildrenArePresent', 3: 'maxSpeedInConstructionZone', 4: 'vehicleMinSpeed', 5: 'vehicleMaxSpeed', 6: 'vehicleNightMaxSpeed', 7: 'truckMinSpeed', 8: 'truckMaxSpeed', 9: 'truckNightMaxSpeed', 10: 'vehiclesWithTrailersMinSpeed', 11: 'vehiclesWithTrailersMaxSpeed', 12: 'vehiclesWithTrailersNightMaxSpeed'}),
        ASN1F_INTEGER("speed", 0, uper_min=0, uper_max=8191, oer_unsigned=True)
    )


class RestrictionUserType(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_ENUMERATED("basicType", 0, {0: 'none', 1: 'equippedTransit', 2: 'equippedTaxis', 3: 'equippedOther', 4: 'emissionCompliant', 5: 'equippedBicycle', 6: 'weightCompliant', 7: 'heightCompliant', 8: 'pedestrians', 9: 'slowMovingPersons', 10: 'wheelchairUsers', 11: 'visualDisabilities', 12: 'audioDisabilities', 13: 'otherUnknownDisabilities'}), uper_extensible=True
    )


class RoadSegmentReferenceID(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_INTEGER("region", None, uper_min=0, uper_max=65535, oer_unsigned=True)),
        ASN1F_INTEGER("id", 0, uper_min=0, uper_max=65535, oer_unsigned=True)
    )


class SignalControlZone(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_STRING("zone", b""), uper_extensible=True
    )


class TimeChangeDetails(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_INTEGER("startTime", None, uper_min=0, uper_max=36001, oer_unsigned=True)),
        ASN1F_INTEGER("minEndTime", 0, uper_min=0, uper_max=36001, oer_unsigned=True),
        ASN1F_optional(ASN1F_INTEGER("maxEndTime", None, uper_min=0, uper_max=36001, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("likelyTime", None, uper_min=0, uper_max=36001, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("confidence", None, uper_min=0, uper_max=15, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("nextTime", None, uper_min=0, uper_max=36001, oer_unsigned=True))
    )


class ITS_Inline_ComputedLane_offsetXaxis(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_INTEGER("small", 0, uper_min=-2047, uper_max=2047),
        ASN1F_INTEGER("large", 0, uper_min=-32767, uper_max=32767)
    )


class ITS_Inline_ComputedLane_offsetYaxis(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_INTEGER("small", 0, uper_min=-2047, uper_max=2047),
        ASN1F_INTEGER("large", 0, uper_min=-32767, uper_max=32767)
    )


class IviManagementContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("serviceProviderId", Provider(), Provider),
        ASN1F_INTEGER("iviIdentificationNumber", 1, uper_min=1, uper_max=32767, oer_unsigned=True),
        ASN1F_optional(ASN1F_INTEGER("timeStamp", None, uper_min=0, uper_max=4398046511103, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("validFrom", None, uper_min=0, uper_max=4398046511103, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("validTo", None, uper_min=0, uper_max=4398046511103, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("connectedIviStructures", None, ASN1F_INTEGER, uper_min=1, uper_max=8)),
        ASN1F_INTEGER("iviStatus", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_optional(ASN1F_SEQUENCE_OF("connectedDenms", None, ActionID, uper_min=1, uper_max=8, uper_extensible=True)), uper_extensible=True
    )


class MlcPart(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("zoneId", 1, uper_min=1, uper_max=32, oer_unsigned=True),
        ASN1F_optional(ASN1F_SEQUENCE_OF("laneIds", None, ASN1F_INTEGER, uper_min=1, uper_max=16, uper_extensible=True))
    )


class AbsolutePosition(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("latitude", 0, uper_min=-900000000, uper_max=900000001),
        ASN1F_INTEGER("longitude", 0, uper_min=-1800000000, uper_max=1800000001)
    )


class AbsolutePositionWAltitude(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("latitude", 0, uper_min=-900000000, uper_max=900000001),
        ASN1F_INTEGER("longitude", 0, uper_min=-1800000000, uper_max=1800000001),
        ASN1F_PACKET("altitude", Altitude(), Altitude)
    )


class ComputedSegment(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("zoneId", 1, uper_min=1, uper_max=32, oer_unsigned=True),
        ASN1F_INTEGER("laneNumber", 0, uper_min=-1, uper_max=14),
        ASN1F_INTEGER("laneWidth", 0, uper_min=0, uper_max=1023, oer_unsigned=True),
        ASN1F_optional(ASN1F_INTEGER("offsetDistance", None, uper_min=-32768, uper_max=32767)),
        ASN1F_optional(ASN1F_PACKET("offsetPosition", None, DeltaReferencePosition))
    )


class DeltaPosition(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("deltaLatitude", 0, uper_min=-131071, uper_max=131072),
        ASN1F_INTEGER("deltaLongitude", 0, uper_min=-131071, uper_max=131072)
    )


class LaneCharacteristics(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("zoneDefinitionAccuracy", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_BOOLEAN("existinglaneMarkingStatus", False),
        ASN1F_INTEGER("newlaneMarkingColour", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_INTEGER("laneDelimitationLeft", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_INTEGER("laneDelimitationRight", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_INTEGER("mergingWith", 1, uper_min=1, uper_max=32, oer_unsigned=True)
    )


class LayoutComponent(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("layoutComponentId", 1, uper_min=1, uper_max=8, oer_unsigned=True),
        ASN1F_INTEGER("height", 10, uper_min=10, uper_max=73, oer_unsigned=True),
        ASN1F_INTEGER("width", 10, uper_min=10, uper_max=265, oer_unsigned=True),
        ASN1F_INTEGER("x", 10, uper_min=10, uper_max=265, oer_unsigned=True),
        ASN1F_INTEGER("y", 10, uper_min=10, uper_max=73, oer_unsigned=True),
        ASN1F_INTEGER("textScripting", 0, uper_min=0, uper_max=1, oer_unsigned=True)
    )


class LoadType(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("goodsType", 0, uper_min=0, uper_max=15, oer_unsigned=True),
        ASN1F_ENUMERATED("dangerousGoodsType", 0, {0: 'explosives1', 1: 'explosives2', 2: 'explosives3', 3: 'explosives4', 4: 'explosives5', 5: 'explosives6', 6: 'flammableGases', 7: 'nonFlammableGases', 8: 'toxicGases', 9: 'flammableLiquids', 10: 'flammableSolids', 11: 'substancesLiableToSpontaneousCombustion', 12: 'substancesEmittingFlammableGasesUponContactWithWater', 13: 'oxidizingSubstances', 14: 'organicPeroxides', 15: 'toxicSubstances', 16: 'infectiousSubstances', 17: 'radioactiveMaterial', 18: 'corrosiveSubstances', 19: 'miscellaneousDangerousSubstances'}),
        ASN1F_FLAGS("specialTransportType", b'', ['heavyLoad', 'excessWidth', 'excessLength', 'excessHeight'], uper_min=4, uper_max=4)
    )


class MapReference(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", RoadSegmentReferenceID(),
        RoadSegmentReferenceID,
        IntersectionReferenceID
    )


class PolygonalLine(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_STRING("deltaPositions", 0, uper_min=1, uper_max=32, size_len=100),
        ASN1F_STRING("deltaPositionsWithAltitude", 0, uper_min=1, uper_max=32, size_len=100),
        ASN1F_STRING("absolutePositions", 0, uper_min=1, uper_max=8),
        ASN1F_STRING("absolutePositionsWithAltitude", 0, uper_min=1, uper_max=8), uper_extensible=True
    )


class RoadSurfaceDynamicCharacteristics(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("condition", 0, uper_min=0, uper_max=15, oer_unsigned=True),
        ASN1F_INTEGER("temperature", 0, uper_min=-100, uper_max=151),
        ASN1F_INTEGER("iceOrWaterDepth", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_INTEGER("treatment", 0, uper_min=0, uper_max=7, oer_unsigned=True)
    )


class RoadSurfaceStaticCharacteristics(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("frictionCoefficient", 0, uper_min=0, uper_max=101, oer_unsigned=True),
        ASN1F_INTEGER("material", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_INTEGER("wear", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_INTEGER("avBankingAngle", 0, uper_min=-20, uper_max=21)
    )


class Segment(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("line", PolygonalLine(), PolygonalLine),
        ASN1F_optional(ASN1F_INTEGER("laneWidth", None, uper_min=0, uper_max=1023, oer_unsigned=True))
    )


class Text(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_INTEGER("layoutComponentId", None, uper_min=1, uper_max=4, oer_unsigned=True)),
        ASN1F_BIT_STRING("language", b'', uper_min=10, uper_max=10),
        ASN1F_UTF8_STRING("textContent", '')
    )


class VehicleCharacteristicsFixValues(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_INTEGER("simpleVehicleType", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        EuVehicleCategoryCode,
        ASN1F_INTEGER("iso3833VehicleType", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        EnvironmentalCharacteristics,
        ASN1F_INTEGER("engineCharacteristics", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        LoadType,
        ASN1F_ENUMERATED("usage", 0, {0: 'default', 1: 'publicTransport', 2: 'specialTransport', 3: 'dangerousGoods', 4: 'roadWork', 5: 'rescue', 6: 'emergency', 7: 'safetyCar', 8: 'agriculture', 9: 'commercial', 10: 'military', 11: 'roadOperator', 12: 'taxi', 13: 'reserved1', 14: 'reserved2', 15: 'reserved3'}), uper_extensible=True
    )


class Zone(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", Segment(),
        Segment,
        PolygonalLine,
        ComputedSegment, uper_extensible=True
    )


class ITS_Inline_ITS_Inline_ISO14823Code_pictogramCode_serviceCategoryCode(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_ENUMERATED("trafficSignPictogram", 0, {0: 'dangerWarning', 1: 'regulatory', 2: 'informative'}),
        ASN1F_ENUMERATED("publicFacilitiesPictogram", 0, {0: 'publicFacilities'}),
        ASN1F_ENUMERATED("ambientOrRoadConditionPictogram", 0, {0: 'ambientCondition', 1: 'roadCondition'}), uper_extensible=True
    )


class ITS_Inline_ITS_Inline_ISO14823Code_pictogramCode_pictogramCategoryCode(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("nature", 1, uper_min=1, uper_max=9, oer_unsigned=True),
        ASN1F_INTEGER("serialNumber", 0, uper_min=0, uper_max=99, oer_unsigned=True)
    )


class Ext2(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_INTEGER("content", 16512, uper_min=16512, uper_max=2113663, oer_unsigned=True),
        ASN1F_INTEGER("extension", 2113664, uper_min=2113664, uper_max=270549119, oer_unsigned=True)
    )


class ReferencePosition(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("latitude", 0, uper_min=-900000000, uper_max=900000001),
        ASN1F_INTEGER("longitude", 0, uper_min=-1800000000, uper_max=1800000001),
        ASN1F_PACKET("positionConfidenceEllipse", PosConfidenceEllipse(), PosConfidenceEllipse),
        ASN1F_PACKET("altitude", Altitude(), Altitude)
    )


class HighFrequencyContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", BasicVehicleContainerHighFrequency(),
        BasicVehicleContainerHighFrequency,
        RSUContainerHighFrequency, uper_extensible=True
    )


class LowFrequencyContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", BasicVehicleContainerLowFrequency(),
        BasicVehicleContainerLowFrequency, uper_extensible=True
    )


class SpecialVehicleContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", PublicTransportContainer(),
        PublicTransportContainer,
        SpecialTransportContainer,
        DangerousGoodsContainer,
        RoadWorksContainerBasic,
        RescueContainer,
        EmergencyContainer,
        SafetyCarContainer, uper_extensible=True
    )


class BasicContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("stationType", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_PACKET("referencePosition", ReferencePosition(), ReferencePosition), uper_extensible=True
    )


class ManagementContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("actionID", ActionID(), ActionID),
        ASN1F_INTEGER("detectionTime", 0, uper_min=0, uper_max=4398046511103, oer_unsigned=True),
        ASN1F_INTEGER("referenceTime", 0, uper_min=0, uper_max=4398046511103, oer_unsigned=True),
        ASN1F_optional(ASN1F_ENUMERATED("termination", 0, {0: 'isCancellation', 1: 'isNegation'})),
        ASN1F_PACKET("eventPosition", ReferencePosition(), ReferencePosition),
        ASN1F_optional(ASN1F_ENUMERATED("relevanceDistance", 0, {0: 'lessThan50m', 1: 'lessThan100m', 2: 'lessThan200m', 3: 'lessThan500m', 4: 'lessThan1000m', 5: 'lessThan5km', 6: 'lessThan10km', 7: 'over10km'})),
        ASN1F_optional(ASN1F_ENUMERATED("relevanceTrafficDirection", 0, {0: 'allTrafficDirections', 1: 'upstreamTraffic', 2: 'downstreamTraffic', 3: 'oppositeTraffic'})),
        ASN1F_DEFAULT(
            ASN1F_INTEGER("validityDuration", 600, uper_min=0, uper_max=86400, oer_unsigned=True),
            600,
        ),
        ASN1F_optional(ASN1F_INTEGER("transmissionInterval", None, uper_min=1, uper_max=10000, oer_unsigned=True)),
        ASN1F_INTEGER("stationType", 0, uper_min=0, uper_max=255, oer_unsigned=True), uper_extensible=True
    )


class RoadWorksContainerExtended(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_FLAGS("lightBarSirenInUse", None, ['lightBarActivated', 'sirenActivated'], uper_min=2, uper_max=2)),
        ASN1F_optional(ASN1F_PACKET("closedLanes", None, ClosedLanes)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("restriction", None, ASN1F_INTEGER, uper_min=1, uper_max=3, uper_extensible=True)),
        ASN1F_optional(ASN1F_INTEGER("speedLimit", None, uper_min=1, uper_max=255, oer_unsigned=True)),
        ASN1F_optional(ASN1F_PACKET("incidentIndication", None, CauseCode)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("recommendedPath", None, ReferencePosition, uper_min=1, uper_max=40)),
        ASN1F_optional(ASN1F_PACKET("startingPointSpeedLimit", None, DeltaReferencePosition)),
        ASN1F_optional(ASN1F_ENUMERATED("trafficFlowRule", 0, {0: 'noPassing', 1: 'noPassingForTrucks', 2: 'passToRight', 3: 'passToLeft'})),
        ASN1F_optional(ASN1F_SEQUENCE_OF("referenceDenms", None, ActionID, uper_min=1, uper_max=8, uper_extensible=True))
    )


class AlacarteContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_INTEGER("lanePosition", None, uper_min=-1, uper_max=14)),
        ASN1F_optional(ASN1F_PACKET("impactReduction", None, ImpactReductionContainer)),
        ASN1F_optional(ASN1F_INTEGER("externalTemperature", None, uper_min=-60, uper_max=67)),
        ASN1F_optional(ASN1F_PACKET("roadWorks", None, RoadWorksContainerExtended)),
        ASN1F_optional(ASN1F_ENUMERATED("positioningSolution", 0, {0: 'noPositioningSolution', 1: 'sGNSS', 2: 'dGNSS', 3: 'sGNSSplusDR', 4: 'dGNSSplusDR', 5: 'dR'})),
        ASN1F_optional(ASN1F_PACKET("stationaryVehicle", None, StationaryVehicleContainer)), uper_extensible=True
    )


class InternationalSign_applicablePeriod(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_PACKET("year", None, ITS_Inline_InternationalSign_applicablePeriod_year)),
        ASN1F_optional(ASN1F_PACKET("month_day", None, ITS_Inline_InternationalSign_applicablePeriod_month_day)),
        ASN1F_optional(ASN1F_FLAGS("repeatingPeriodDayTypes", None, ['national-holiday', 'even-days', 'odd-days', 'market-day'], uper_min=4, uper_max=4)),
        ASN1F_optional(ASN1F_PACKET("hourMinutes", None, ITS_Inline_InternationalSign_applicablePeriod_hourMinutes)),
        ASN1F_optional(ASN1F_FLAGS("dateRangeOfWeek", None, ['unused', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'], uper_min=8, uper_max=8)),
        ASN1F_optional(ASN1F_PACKET("durationHourMinute", None, HoursMinutes))
    )


class InternationalSign_applicableVehicleDimensions(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_PACKET("vehicleHeight", None, Distance)),
        ASN1F_optional(ASN1F_PACKET("vehicleWidth", None, Distance)),
        ASN1F_optional(ASN1F_PACKET("vehicleLength", None, Distance)),
        ASN1F_optional(ASN1F_PACKET("vehicleWeight", None, Weight))
    )


class InternationalSign_section(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_PACKET("startingPointLength", None, Distance)),
        ASN1F_optional(ASN1F_PACKET("continuityLength", None, Distance))
    )


class ITS_Inline_GddStructure_pictogramCode(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_STRING("countryCode", None, size_len=2)),
        ASN1F_PACKET("serviceCategoryCode", ITS_Inline_ITS_Inline_GddStructure_pictogramCode_serviceCategoryCode(), ITS_Inline_ITS_Inline_GddStructure_pictogramCode_serviceCategoryCode),
        ASN1F_PACKET("pictogramCategoryCode", ITS_Inline_ITS_Inline_GddStructure_pictogramCode_pictogramCategoryCode(), ITS_Inline_ITS_Inline_GddStructure_pictogramCode_pictogramCategoryCode)
    )


class DieselEmissionValues(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("particulate", ITS_Inline_DieselEmissionValues_particulate(), ITS_Inline_DieselEmissionValues_particulate),
        ASN1F_INTEGER("absorptionCoeff", 0, uper_min=0, uper_max=65535, oer_unsigned=True)
    )


class ComputedLane(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("referenceLaneId", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_PACKET("offsetXaxis", ITS_Inline_ComputedLane_offsetXaxis(), ITS_Inline_ComputedLane_offsetXaxis),
        ASN1F_PACKET("offsetYaxis", ITS_Inline_ComputedLane_offsetYaxis(), ITS_Inline_ComputedLane_offsetYaxis),
        ASN1F_optional(ASN1F_INTEGER("rotateXY", None, uper_min=0, uper_max=28800, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("scaleXaxis", None, uper_min=-2048, uper_max=2047)),
        ASN1F_optional(ASN1F_INTEGER("scaleYaxis", None, uper_min=-2048, uper_max=2047)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class Connection(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("connectingLane", ConnectingLane(), ConnectingLane),
        ASN1F_optional(ASN1F_PACKET("remoteIntersection", None, IntersectionReferenceID)),
        ASN1F_optional(ASN1F_INTEGER("signalGroup", None, uper_min=0, uper_max=255, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("userClass", None, uper_min=0, uper_max=255, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("connectionID", None, uper_min=0, uper_max=255, oer_unsigned=True))
    )


class LaneAttributes(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_FLAGS("directionalUse", b'', ['ingressPath', 'egressPath'], uper_min=2, uper_max=2),
        ASN1F_FLAGS("sharedWith", b'', ['overlappingLaneDescriptionProvided', 'multipleLanesTreatedAsOneLane', 'otherNonMotorizedTrafficTypes', 'individualMotorizedVehicleTraffic', 'busVehicleTraffic', 'taxiVehicleTraffic', 'pedestriansTraffic', 'cyclistVehicleTraffic', 'trackedVehicleTraffic', 'pedestrianTraffic'], uper_min=10, uper_max=10),
        ASN1F_PACKET("laneType", LaneTypeAttributes(), LaneTypeAttributes),
        ASN1F_optional(ASN1F_STRING("regional", b""))
    )


class LaneDataAttribute(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_INTEGER("pathEndPointAngle", 0, uper_min=-150, uper_max=150),
        ASN1F_INTEGER("laneCrownPointCenter", 0, uper_min=-128, uper_max=127),
        ASN1F_INTEGER("laneCrownPointLeft", 0, uper_min=-128, uper_max=127),
        ASN1F_INTEGER("laneCrownPointRight", 0, uper_min=-128, uper_max=127),
        ASN1F_INTEGER("laneAngle", 0, uper_min=-180, uper_max=180),
        ASN1F_STRING("speedLimits", 0, uper_min=1, uper_max=9), uper_extensible=True
    )


class MovementEvent(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_ENUMERATED("eventState", 0, {0: 'unavailable', 1: 'dark', 2: 'stop-Then-Proceed', 3: 'stop-And-Remain', 4: 'pre-Movement', 5: 'permissive-Movement-Allowed', 6: 'protected-Movement-Allowed', 7: 'permissive-clearance', 8: 'protected-clearance', 9: 'caution-Conflicting-Traffic'}),
        ASN1F_optional(ASN1F_PACKET("timing", None, TimeChangeDetails)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("speeds", None, AdvisorySpeed, uper_min=1, uper_max=16)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class MovementState(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_IA5_STRING("movementName", None, uper_min=1, uper_max=63)),
        ASN1F_INTEGER("signalGroup", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_SEQUENCE_OF("state_time_speed", [MovementEvent()], MovementEvent, uper_min=1, uper_max=16),
        ASN1F_optional(ASN1F_SEQUENCE_OF("maneuverAssistList", None, ConnectionManeuverAssist, uper_min=1, uper_max=16)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class NodeAttributeSetXY(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_SEQUENCE_OF("localNode", None, ASN1F_ENUMERATED("item", 0, {0: 'reserved', 1: 'stopLine', 2: 'roundedCapStyleA', 3: 'roundedCapStyleB', 4: 'mergePoint', 5: 'divergePoint', 6: 'downstreamStopLine', 7: 'downstreamStartNode', 8: 'closedToTraffic', 9: 'safeIsland', 10: 'curbPresentAtStepOff', 11: 'hydrantPresent'}), uper_min=1, uper_max=8)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("disabled", None, ASN1F_ENUMERATED("item", 0, {0: 'reserved', 1: 'doNotBlock', 2: 'whiteLine', 3: 'mergingLaneLeft', 4: 'mergingLaneRight', 5: 'curbOnLeft', 6: 'curbOnRight', 7: 'loadingzoneOnLeft', 8: 'loadingzoneOnRight', 9: 'turnOutPointOnLeft', 10: 'turnOutPointOnRight', 11: 'adjacentParkingOnLeft', 12: 'adjacentParkingOnRight', 13: 'adjacentBikeLaneOnLeft', 14: 'adjacentBikeLaneOnRight', 15: 'sharedBikeLane', 16: 'bikeBoxInFront', 17: 'transitStopOnLeft', 18: 'transitStopOnRight', 19: 'transitStopInLane', 20: 'sharedWithTrackedVehicle', 21: 'safeIsland', 22: 'lowCurbsPresent', 23: 'rumbleStripPresent', 24: 'audibleSignalingPresent', 25: 'adaptiveTimingPresent', 26: 'rfSignalRequestPresent', 27: 'partialCurbIntrusion', 28: 'taperToLeft', 29: 'taperToRight', 30: 'taperToCenterLine', 31: 'parallelParking', 32: 'headInParking', 33: 'freeParking', 34: 'timeRestrictionsOnParking', 35: 'costToPark', 36: 'midBlockCurbPresent', 37: 'unEvenPavementPresent'}), uper_min=1, uper_max=8)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("enabled", None, ASN1F_ENUMERATED("item", 0, {0: 'reserved', 1: 'doNotBlock', 2: 'whiteLine', 3: 'mergingLaneLeft', 4: 'mergingLaneRight', 5: 'curbOnLeft', 6: 'curbOnRight', 7: 'loadingzoneOnLeft', 8: 'loadingzoneOnRight', 9: 'turnOutPointOnLeft', 10: 'turnOutPointOnRight', 11: 'adjacentParkingOnLeft', 12: 'adjacentParkingOnRight', 13: 'adjacentBikeLaneOnLeft', 14: 'adjacentBikeLaneOnRight', 15: 'sharedBikeLane', 16: 'bikeBoxInFront', 17: 'transitStopOnLeft', 18: 'transitStopOnRight', 19: 'transitStopInLane', 20: 'sharedWithTrackedVehicle', 21: 'safeIsland', 22: 'lowCurbsPresent', 23: 'rumbleStripPresent', 24: 'audibleSignalingPresent', 25: 'adaptiveTimingPresent', 26: 'rfSignalRequestPresent', 27: 'partialCurbIntrusion', 28: 'taperToLeft', 29: 'taperToRight', 30: 'taperToCenterLine', 31: 'parallelParking', 32: 'headInParking', 33: 'freeParking', 34: 'timeRestrictionsOnParking', 35: 'costToPark', 36: 'midBlockCurbPresent', 37: 'unEvenPavementPresent'}), uper_min=1, uper_max=8)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("data", None, LaneDataAttribute, uper_min=1, uper_max=8)),
        ASN1F_optional(ASN1F_INTEGER("dWidth", None, uper_min=-512, uper_max=511)),
        ASN1F_optional(ASN1F_INTEGER("dElevation", None, uper_min=-512, uper_max=511)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class NodeXY(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("delta", NodeOffsetPointXY(), NodeOffsetPointXY),
        ASN1F_optional(ASN1F_PACKET("attributes", None, NodeAttributeSetXY)), uper_extensible=True
    )


class RestrictionClassAssignment(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("id", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_SEQUENCE_OF("users", [RestrictionUserType()], RestrictionUserType, uper_min=1, uper_max=16)
    )


class GlcPart(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("zoneId", 1, uper_min=1, uper_max=32, oer_unsigned=True),
        ASN1F_optional(ASN1F_INTEGER("laneNumber", None, uper_min=-1, uper_max=14)),
        ASN1F_optional(ASN1F_INTEGER("zoneExtension", None, uper_min=0, uper_max=255, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("zoneHeading", None, uper_min=0, uper_max=3601, oer_unsigned=True)),
        ASN1F_optional(ASN1F_PACKET("zone", None, Zone)), uper_extensible=True
    )


class RscPart(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_SEQUENCE_OF("detectionZoneIds", None, ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_SEQUENCE_OF("relevanceZoneIds", [], ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True),
        ASN1F_optional(ASN1F_INTEGER("direction", None, uper_min=0, uper_max=3, oer_unsigned=True)),
        ASN1F_optional(ASN1F_PACKET("roadSurfaceStaticCharacteristics", None, RoadSurfaceStaticCharacteristics)),
        ASN1F_optional(ASN1F_PACKET("roadSurfaceDynamicCharacteristics", None, RoadSurfaceDynamicCharacteristics))
    )


class LayoutContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("layoutId", 1, uper_min=1, uper_max=4, oer_unsigned=True),
        ASN1F_optional(ASN1F_INTEGER("height", None, uper_min=10, uper_max=73, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("width", None, uper_min=10, uper_max=265, oer_unsigned=True)),
        ASN1F_SEQUENCE_OF("layoutComponents", [LayoutComponent()], LayoutComponent, uper_min=1, uper_max=4, uper_extensible=True), uper_extensible=True
    )


class MapLocationContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("reference", MapReference(), MapReference),
        ASN1F_SEQUENCE_OF("parts", [MlcPart()], MlcPart, uper_min=1, uper_max=16, uper_extensible=True)
    )


class VcCode(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("roadSignClass", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_INTEGER("roadSignCode", 1, uper_min=1, uper_max=64, oer_unsigned=True),
        ASN1F_INTEGER("vcOption", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_optional(ASN1F_SEQUENCE_OF("validity", None, InternationalSign_applicablePeriod, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_optional(ASN1F_INTEGER("value", None, uper_min=0, uper_max=65535, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("unit", None, uper_min=0, uper_max=15, oer_unsigned=True))
    )


class ITS_Inline_ISO14823Code_pictogramCode(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_STRING("countryCode", None, size_len=2)),
        ASN1F_PACKET("serviceCategoryCode", ITS_Inline_ITS_Inline_ISO14823Code_pictogramCode_serviceCategoryCode(), ITS_Inline_ITS_Inline_ISO14823Code_pictogramCode_serviceCategoryCode),
        ASN1F_PACKET("pictogramCategoryCode", ITS_Inline_ITS_Inline_ISO14823Code_pictogramCode_pictogramCategoryCode(), ITS_Inline_ITS_Inline_ISO14823Code_pictogramCode_pictogramCategoryCode)
    )


class ITS_Inline_VehicleCharacteristicsRanges_limits(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_INTEGER("numberOfAxles", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        VehicleDimensions,
        VehicleWeightLimits,
        AxleWeightLimits,
        PassengerCapacity,
        ExhaustEmissionValues,
        DieselEmissionValues,
        SoundLevel, uper_extensible=True
    )


class Ext1(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_INTEGER("content", 128, uper_min=128, uper_max=16511, oer_unsigned=True),
        Ext2
    )


class CamParameters(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("basicContainer", BasicContainer(), BasicContainer),
        ASN1F_PACKET("highFrequencyContainer", HighFrequencyContainer(), HighFrequencyContainer),
        ASN1F_optional(ASN1F_PACKET("lowFrequencyContainer", None, LowFrequencyContainer)),
        ASN1F_optional(ASN1F_PACKET("specialVehicleContainer", None, SpecialVehicleContainer)), uper_extensible=True
    )


class DecentralizedEnvironmentalNotificationMessage(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("management", ManagementContainer(), ManagementContainer),
        ASN1F_optional(ASN1F_PACKET("situation", None, SituationContainer)),
        ASN1F_optional(ASN1F_PACKET("location", None, LocationContainer)),
        ASN1F_optional(ASN1F_PACKET("alacarte", None, AlacarteContainer))
    )


class IntersectionState(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_IA5_STRING("name_", None, uper_min=1, uper_max=63)),
        ASN1F_PACKET("id", IntersectionReferenceID(), IntersectionReferenceID),
        ASN1F_INTEGER("revision", 0, uper_min=0, uper_max=127, oer_unsigned=True),
        ASN1F_FLAGS("status", b'', ['manualControlIsEnabled', 'stopTimeIsActivated', 'failureFlash', 'preemptIsActive', 'signalPriorityIsActive', 'fixedTimeOperation', 'trafficDependentOperation', 'standbyOperation', 'failureMode', 'off', 'recentMAPmessageUpdate', 'recentChangeInMAPassignedLanesIDsUsed', 'noValidMAPisAvailableAtThisTime', 'noValidSPATisAvailableAtThisTime'], uper_min=16, uper_max=16),
        ASN1F_optional(ASN1F_INTEGER("moy", None, uper_min=0, uper_max=527040, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("timeStamp", None, uper_min=0, uper_max=65535, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("enabledLanes", None, ASN1F_INTEGER, uper_min=1, uper_max=16)),
        ASN1F_SEQUENCE_OF("states", [MovementState()], MovementState, uper_min=1, uper_max=255),
        ASN1F_optional(ASN1F_SEQUENCE_OF("maneuverAssistList", None, ConnectionManeuverAssist, uper_min=1, uper_max=16)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class NodeListXY(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_STRING("nodes", 0, uper_min=2, uper_max=63),
        ComputedLane, uper_extensible=True
    )


class GeographicLocationContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("referencePosition", ReferencePosition(), ReferencePosition),
        ASN1F_optional(ASN1F_INTEGER("referencePositionTime", None, uper_min=0, uper_max=4398046511103, oer_unsigned=True)),
        ASN1F_optional(ASN1F_PACKET("referencePositionHeading", None, Heading)),
        ASN1F_optional(ASN1F_PACKET("referencePositionSpeed", None, Speed)),
        ASN1F_SEQUENCE_OF("parts", [GlcPart()], GlcPart, uper_min=1, uper_max=16, uper_extensible=True), uper_extensible=True
    )


class VehicleCharacteristicsRanges(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("comparisonOperator", 0, uper_min=0, uper_max=3, oer_unsigned=True),
        ASN1F_PACKET("limits", ITS_Inline_VehicleCharacteristicsRanges_limits(), ITS_Inline_VehicleCharacteristicsRanges_limits)
    )


class VarLengthNumber(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", None,
        ASN1F_INTEGER("content", 0, uper_min=0, uper_max=127, oer_unsigned=True),
        Ext1
    )


class CoopAwareness(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("generationDeltaTime", 0, uper_min=0, uper_max=65535, oer_unsigned=True),
        ASN1F_PACKET("camParameters", CamParameters(), CamParameters)
    )


class SPAT(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_INTEGER("timeStamp", None, uper_min=0, uper_max=527040, oer_unsigned=True)),
        ASN1F_optional(ASN1F_IA5_STRING("name_", None, uper_min=1, uper_max=63)),
        ASN1F_SEQUENCE_OF("intersections", [IntersectionState()], IntersectionState, uper_min=1, uper_max=32),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class GenericLane(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("laneID", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_optional(ASN1F_IA5_STRING("name_", None, uper_min=1, uper_max=63)),
        ASN1F_optional(ASN1F_INTEGER("ingressApproach", None, uper_min=0, uper_max=15, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("egressApproach", None, uper_min=0, uper_max=15, oer_unsigned=True)),
        ASN1F_PACKET("laneAttributes", LaneAttributes(), LaneAttributes),
        ASN1F_optional(ASN1F_FLAGS("maneuvers", None, ['maneuverStraightAllowed', 'maneuverLeftAllowed', 'maneuverRightAllowed', 'maneuverUTurnAllowed', 'maneuverLeftTurnOnRedAllowed', 'maneuverRightTurnOnRedAllowed', 'maneuverLaneChangeAllowed', 'maneuverNoStoppingAllowed', 'yieldAllwaysRequired', 'goWithHalt', 'caution', 'reserved1'], uper_min=12, uper_max=12)),
        ASN1F_PACKET("nodeList", NodeListXY(), NodeListXY),
        ASN1F_optional(ASN1F_SEQUENCE_OF("connectsTo", None, Connection, uper_min=1, uper_max=16)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("overlays", None, ASN1F_INTEGER, uper_min=1, uper_max=5)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class IntersectionGeometry(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_IA5_STRING("name_", None, uper_min=1, uper_max=63)),
        ASN1F_PACKET("id", IntersectionReferenceID(), IntersectionReferenceID),
        ASN1F_INTEGER("revision", 0, uper_min=0, uper_max=127, oer_unsigned=True),
        ASN1F_PACKET("refPoint", Position3D(), Position3D),
        ASN1F_optional(ASN1F_INTEGER("laneWidth", None, uper_min=0, uper_max=32767, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("speedLimits", None, RegulatorySpeedLimit, uper_min=1, uper_max=9)),
        ASN1F_SEQUENCE_OF("laneSet", [GenericLane()], GenericLane, uper_min=1, uper_max=255),
        ASN1F_optional(ASN1F_SEQUENCE_OF("preemptPriorityData", None, SignalControlZone, uper_min=1, uper_max=32)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class RoadSegment(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_IA5_STRING("name_", None, uper_min=1, uper_max=63)),
        ASN1F_PACKET("id", RoadSegmentReferenceID(), RoadSegmentReferenceID),
        ASN1F_INTEGER("revision", 0, uper_min=0, uper_max=127, oer_unsigned=True),
        ASN1F_PACKET("refPoint", Position3D(), Position3D),
        ASN1F_optional(ASN1F_INTEGER("laneWidth", None, uper_min=0, uper_max=32767, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("speedLimits", None, RegulatorySpeedLimit, uper_min=1, uper_max=9)),
        ASN1F_SEQUENCE_OF("roadLaneSet", [GenericLane()], GenericLane, uper_min=1, uper_max=255),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class TractorCharacteristics(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_SEQUENCE_OF("equalTo", None, VehicleCharacteristicsFixValues, uper_min=1, uper_max=4, uper_extensible=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("notEqualTo", None, VehicleCharacteristicsFixValues, uper_min=1, uper_max=4, uper_extensible=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("ranges", None, VehicleCharacteristicsRanges, uper_min=1, uper_max=4, uper_extensible=True))
    )


class IVI_TrailerCharacteristics(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_SEQUENCE_OF("equalTo", None, VehicleCharacteristicsFixValues, uper_min=1, uper_max=4, uper_extensible=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("notEqualTo", None, VehicleCharacteristicsFixValues, uper_min=1, uper_max=4, uper_extensible=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("ranges", None, VehicleCharacteristicsRanges, uper_min=1, uper_max=4, uper_extensible=True))
    )


class MapData(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_INTEGER("timeStamp", None, uper_min=0, uper_max=527040, oer_unsigned=True)),
        ASN1F_INTEGER("msgIssueRevision", 0, uper_min=0, uper_max=127, oer_unsigned=True),
        ASN1F_optional(ASN1F_ENUMERATED("layerType", 0, {0: 'none', 1: 'mixedContent', 2: 'generalMapData', 3: 'intersectionData', 4: 'curveData', 5: 'roadwaySectionData', 6: 'parkingAreaData', 7: 'sharedLaneData'})),
        ASN1F_optional(ASN1F_INTEGER("layerID", None, uper_min=0, uper_max=100, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("intersections", None, IntersectionGeometry, uper_min=1, uper_max=32)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("roadSegments", None, RoadSegment, uper_min=1, uper_max=32)),
        ASN1F_optional(ASN1F_PACKET("dataParameters", None, DataParameters)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("restrictionList", None, RestrictionClassAssignment, uper_min=1, uper_max=254)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("regional", None, ASN1F_STRING)), uper_extensible=True
    )


class CompleteVehicleCharacteristics(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_PACKET("tractor", None, TractorCharacteristics)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("trailer", None, IVI_TrailerCharacteristics, uper_min=1, uper_max=3)),
        ASN1F_optional(ASN1F_PACKET("train", None, TractorCharacteristics))
    )


class LaneInformation(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("laneNumber", 0, uper_min=-1, uper_max=14),
        ASN1F_INTEGER("direction", 0, uper_min=0, uper_max=3, oer_unsigned=True),
        ASN1F_optional(ASN1F_PACKET("validity", None, InternationalSign_applicablePeriod)),
        ASN1F_INTEGER("laneType", 0, uper_min=0, uper_max=31, oer_unsigned=True),
        ASN1F_optional(ASN1F_PACKET("laneTypeQualifier", None, CompleteVehicleCharacteristics)),
        ASN1F_INTEGER("laneStatus", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_optional(ASN1F_INTEGER("laneWidth", None, uper_min=0, uper_max=1023, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("detectionZoneIds", None, ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("relevanceZoneIds", None, ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_optional(ASN1F_PACKET("laneCharacteristics", None, LaneCharacteristics)),
        ASN1F_optional(ASN1F_PACKET("laneSurfaceStaticCharacteristics", None, RoadSurfaceStaticCharacteristics)),
        ASN1F_optional(ASN1F_PACKET("laneSurfaceDynamicCharacteristics", None, RoadSurfaceDynamicCharacteristics)), uper_extensible=True
    )


class RccPart(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_SEQUENCE_OF("relevanceZoneIds", [], ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True),
        ASN1F_ENUMERATED("roadType", 0, {0: 'urban-NoStructuralSeparationToOppositeLanes', 1: 'urban-WithStructuralSeparationToOppositeLanes', 2: 'nonUrban-NoStructuralSeparationToOppositeLanes', 3: 'nonUrban-WithStructuralSeparationToOppositeLanes'}),
        ASN1F_SEQUENCE_OF("laneConfiguration", [LaneInformation()], LaneInformation, uper_min=1, uper_max=16, uper_extensible=True), uper_extensible=True
    )


class TcPart(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_SEQUENCE_OF("detectionZoneIds", None, ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_SEQUENCE_OF("relevanceZoneIds", [], ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True),
        ASN1F_optional(ASN1F_INTEGER("direction", None, uper_min=0, uper_max=3, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("driverAwarenessZoneIds", None, ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_optional(ASN1F_INTEGER("minimumAwarenessTime", None, uper_min=0, uper_max=255, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("applicableLanes", None, ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_optional(ASN1F_INTEGER("layoutId", None, uper_min=1, uper_max=4, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("preStoredlayoutId", None, uper_min=1, uper_max=64, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("text", None, Text, uper_min=1, uper_max=4, uper_extensible=True)),
        ASN1F_STRING("data", b''),
        ASN1F_INTEGER("iviType", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_optional(ASN1F_INTEGER("laneStatus", None, uper_min=0, uper_max=7, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("vehicleCharacteristics", None, CompleteVehicleCharacteristics, uper_min=1, uper_max=8, uper_extensible=True)), uper_extensible=True
    )


class IviContainer(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", GeographicLocationContainer(),
        GeographicLocationContainer,
        ASN1F_STRING("giv", 0, uper_min=1, uper_max=16),
        ASN1F_STRING("rcc", 0, uper_min=1, uper_max=16),
        ASN1F_STRING("tc", 0, uper_min=1, uper_max=16),
        LayoutContainer,
        ASN1F_STRING("avc", 0, uper_min=1, uper_max=16),
        MapLocationContainer,
        ASN1F_STRING("rsc", 0, uper_min=1, uper_max=16), uper_extensible=True
    )


class IviStructure(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("mandatory", IviManagementContainer(), IviManagementContainer),
        ASN1F_optional(ASN1F_SEQUENCE_OF("optional", None, IviContainer, uper_min=1, uper_max=8, uper_extensible=True))
    )


class GddAttribute(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", InternationalSign_applicablePeriod(),
        InternationalSign_applicablePeriod,
        InternationalSign_applicablePeriod,
        ASN1F_INTEGER("dfl", 1, uper_min=1, uper_max=8, oer_unsigned=True),
        InternationalSign_applicableVehicleDimensions,
        InternationalSign_speedLimits,
        ASN1F_INTEGER("roi", 1, uper_min=1, uper_max=32, oer_unsigned=True),
        Distance,
        ASN1F_STRING("ddd", b''),
        InternationalSign_section,
        ASN1F_INTEGER("nol", 0, uper_min=0, uper_max=99, oer_unsigned=True)
    )


class GddStructure(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("pictogramCode", ITS_Inline_GddStructure_pictogramCode(), ITS_Inline_GddStructure_pictogramCode),
        ASN1F_optional(ASN1F_SEQUENCE_OF("attributes", None, GddAttribute, uper_min=1, uper_max=8, uper_extensible=True))
    )


class DestinationPlace(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("destType", 0, uper_min=0, uper_max=15, oer_unsigned=True),
        ASN1F_optional(ASN1F_PACKET("destRSCode", None, GddStructure)),
        ASN1F_optional(ASN1F_STRING("destBlob", None)),
        ASN1F_optional(ASN1F_INTEGER("placeNameIdentification", None, uper_min=1, uper_max=999, oer_unsigned=True)),
        ASN1F_optional(ASN1F_UTF8_STRING("placeNameText", None))
    )


class DDD_IO(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("arrowDirection", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_optional(ASN1F_SEQUENCE_OF("destPlace", None, DestinationPlace, uper_min=1, uper_max=4, uper_extensible=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("destRoad", None, DestinationRoad, uper_min=1, uper_max=4, uper_extensible=True)),
        ASN1F_optional(ASN1F_INTEGER("roadNumberIdentifier", None, uper_min=1, uper_max=999, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("streetName", None, uper_min=1, uper_max=999, oer_unsigned=True)),
        ASN1F_optional(ASN1F_UTF8_STRING("streetNameText", None)),
        ASN1F_optional(ASN1F_PACKET("distanceToDivergingPoint", None, DistanceOrDuration)),
        ASN1F_optional(ASN1F_PACKET("distanceToDestinationPlace", None, DistanceOrDuration))
    )


class InternationalSign_destinationInformation(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_INTEGER("junctionDirection", None, uper_min=1, uper_max=128, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("roundaboutCwDirection", None, uper_min=1, uper_max=128, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("roundaboutCcwDirection", None, uper_min=1, uper_max=128, oer_unsigned=True)),
        ASN1F_SEQUENCE_OF("ioList", [DDD_IO()], DDD_IO, uper_min=1, uper_max=8, uper_extensible=True)
    )


class ISO14823Attribute(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", InternationalSign_applicablePeriod(),
        InternationalSign_applicablePeriod,
        InternationalSign_applicablePeriod,
        ASN1F_INTEGER("dfl", 1, uper_min=1, uper_max=8, oer_unsigned=True),
        InternationalSign_applicableVehicleDimensions,
        InternationalSign_speedLimits,
        ASN1F_INTEGER("roi", 1, uper_min=1, uper_max=32, oer_unsigned=True),
        Distance,
        InternationalSign_destinationInformation
    )


class ISO14823Code(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("pictogramCode", ITS_Inline_ISO14823Code_pictogramCode(), ITS_Inline_ISO14823Code_pictogramCode),
        ASN1F_optional(ASN1F_SEQUENCE_OF("attributes", None, ISO14823Attribute, uper_min=1, uper_max=8, uper_extensible=True))
    )


class AnyCatalogue(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("owner", Provider(), Provider),
        ASN1F_INTEGER("version", 0, uper_min=0, uper_max=255, oer_unsigned=True),
        ASN1F_INTEGER("pictogramCode", 0, uper_min=0, uper_max=65535, oer_unsigned=True),
        ASN1F_optional(ASN1F_INTEGER("value", None, uper_min=0, uper_max=65535, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("unit", None, uper_min=0, uper_max=15, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("attributes", None, ISO14823Attribute, uper_min=1, uper_max=8, uper_extensible=True))
    )


class ITS_Inline_RSCode_code(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_CHOICE(
        "root", VcCode(),
        VcCode,
        ISO14823Code,
        ASN1F_INTEGER("itisCodes", 0, uper_min=0, uper_max=65535, oer_unsigned=True),
        AnyCatalogue, uper_extensible=True
    )


class RSCode(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_INTEGER("layoutComponentId", None, uper_min=1, uper_max=4, oer_unsigned=True)),
        ASN1F_PACKET("code", ITS_Inline_RSCode_code(), ITS_Inline_RSCode_code)
    )


class GicPart(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_SEQUENCE_OF("detectionZoneIds", None, ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_optional(ASN1F_PACKET("its_Rrid", None, VarLengthNumber)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("relevanceZoneIds", None, ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_optional(ASN1F_INTEGER("direction", None, uper_min=0, uper_max=3, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("driverAwarenessZoneIds", None, ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_optional(ASN1F_INTEGER("minimumAwarenessTime", None, uper_min=0, uper_max=255, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("applicableLanes", None, ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_INTEGER("iviType", 0, uper_min=0, uper_max=7, oer_unsigned=True),
        ASN1F_optional(ASN1F_INTEGER("iviPurpose", None, uper_min=0, uper_max=3, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("laneStatus", None, uper_min=0, uper_max=7, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("vehicleCharacteristics", None, CompleteVehicleCharacteristics, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_optional(ASN1F_INTEGER("driverCharacteristics", None, uper_min=0, uper_max=3, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("layoutId", None, uper_min=1, uper_max=4, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("preStoredlayoutId", None, uper_min=1, uper_max=64, oer_unsigned=True)),
        ASN1F_SEQUENCE_OF("roadSignCodes", [RSCode()], RSCode, uper_min=1, uper_max=4, uper_extensible=True),
        ASN1F_optional(ASN1F_SEQUENCE_OF("extraText", None, Text, uper_min=1, uper_max=4, uper_extensible=True)), uper_extensible=True
    )


class AutomatedVehicleRule(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("priority", 0, uper_min=0, uper_max=2, oer_unsigned=True),
        ASN1F_SEQUENCE_OF("allowedSaeAutomationLevels", [], ASN1F_INTEGER, uper_min=1, uper_max=5),
        ASN1F_optional(ASN1F_INTEGER("minGapBetweenVehicles", None, uper_min=0, uper_max=255, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("recGapBetweenVehicles", None, uper_min=0, uper_max=255, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("automatedVehicleMaxSpeedLimit", None, uper_min=0, uper_max=16383, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("automatedVehicleMinSpeedLimit", None, uper_min=0, uper_max=16383, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("automatedVehicleSpeedRecommendation", None, uper_min=0, uper_max=16383, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("roadSignCodes", None, RSCode, uper_min=1, uper_max=4, uper_extensible=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("extraText", None, Text, uper_min=1, uper_max=4, uper_extensible=True)), uper_extensible=True
    )


class PlatooningRule(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_INTEGER("priority", 0, uper_min=0, uper_max=2, oer_unsigned=True),
        ASN1F_SEQUENCE_OF("allowedSaeAutomationLevels", [], ASN1F_INTEGER, uper_min=1, uper_max=5),
        ASN1F_optional(ASN1F_INTEGER("maxNoOfVehicles", None, uper_min=2, uper_max=64, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("maxLenghtOfPlatoon", None, uper_min=1, uper_max=64, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("minGapBetweenVehicles", None, uper_min=0, uper_max=255, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("platoonMaxSpeedLimit", None, uper_min=0, uper_max=16383, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("platoonMinSpeedLimit", None, uper_min=0, uper_max=16383, oer_unsigned=True)),
        ASN1F_optional(ASN1F_INTEGER("platoonSpeedRecommendation", None, uper_min=0, uper_max=16383, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("roadSignCodes", None, RSCode, uper_min=1, uper_max=4, uper_extensible=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("extraText", None, Text, uper_min=1, uper_max=4, uper_extensible=True)), uper_extensible=True
    )


class AvcPart(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_optional(ASN1F_SEQUENCE_OF("detectionZoneIds", None, ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_SEQUENCE_OF("relevanceZoneIds", [], ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True),
        ASN1F_optional(ASN1F_INTEGER("direction", None, uper_min=0, uper_max=3, oer_unsigned=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("applicableLanes", None, ASN1F_INTEGER, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("vehicleCharacteristics", None, CompleteVehicleCharacteristics, uper_min=1, uper_max=8, uper_extensible=True)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("automatedVehicleRules", None, AutomatedVehicleRule, uper_min=1, uper_max=5)),
        ASN1F_optional(ASN1F_SEQUENCE_OF("platooningRules", None, PlatooningRule, uper_min=1, uper_max=5)), uper_extensible=True
    )


class CAM(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("header", ItsPduHeader(), ItsPduHeader),
        ASN1F_PACKET("cam", CoopAwareness(), CoopAwareness)
    )


class DENM(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("header", ItsPduHeader(), ItsPduHeader),
        ASN1F_PACKET("denm", DecentralizedEnvironmentalNotificationMessage(), DecentralizedEnvironmentalNotificationMessage)
    )


class IVIM(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("header", ItsPduHeader(), ItsPduHeader),
        ASN1F_PACKET("ivi", IviStructure(), IviStructure)
    )


class SPATEM(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("header", ItsPduHeader(), ItsPduHeader),
        ASN1F_PACKET("spat", SPAT(), SPAT)
    )


class MAPEM(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.PER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_PACKET("header", ItsPduHeader(), ItsPduHeader),
        ASN1F_PACKET("map", MapData(), MapData)
    )


CAM = CAM
DENM = DENM
IVIM = IVIM
SPATEM = SPATEM
MAPEM = MAPEM

__all__ = [
    "CAM",
    "DENM",
    "IVIM",
    "SPATEM",
    "MAPEM",
    "ItsPduHeader",
    "DeltaReferencePosition",
    "Altitude",
    "PosConfidenceEllipse",
    "PathPoint",
    "PathHistory",
    "PtActivation",
    "CauseCode",
    "Curvature",
    "Heading",
    "ClosedLanes",
    "Speed",
    "LongitudinalAcceleration",
    "LateralAcceleration",
    "VerticalAcceleration",
    "DangerousGoodsExtended",
    "VehicleIdentification",
    "VehicleLength",
    "SteeringWheelAngle",
    "YawRate",
    "ActionID",
    "ProtectedCommunicationZone",
    "EventPoint",
    "CenDsrcTollingZone",
    "BasicVehicleContainerHighFrequency",
    "BasicVehicleContainerLowFrequency",
    "PublicTransportContainer",
    "SpecialTransportContainer",
    "DangerousGoodsContainer",
    "RoadWorksContainerBasic",
    "RescueContainer",
    "EmergencyContainer",
    "SafetyCarContainer",
    "RSUContainerHighFrequency",
    "SituationContainer",
    "LocationContainer",
    "ImpactReductionContainer",
    "StationaryVehicleContainer",
    "EuVehicleCategoryCode",
    "InternationalSign_speedLimits",
    "DestinationRoad",
    "Distance",
    "DistanceOrDuration",
    "HoursMinutes",
    "MonthDay",
    "Weight",
    "ITS_Inline_InternationalSign_applicablePeriod_year",
    "ITS_Inline_InternationalSign_applicablePeriod_month_day",
    "ITS_Inline_InternationalSign_applicablePeriod_hourMinutes",
    "ITS_Inline_ITS_Inline_GddStructure_pictogramCode_serviceCategoryCode",
    "ITS_Inline_ITS_Inline_GddStructure_pictogramCode_pictogramCategoryCode",
    "AxleWeightLimits",
    "EnvironmentalCharacteristics",
    "ExhaustEmissionValues",
    "PassengerCapacity",
    "Provider",
    "SoundLevel",
    "VehicleDimensions",
    "VehicleWeightLimits",
    "ITS_Inline_DieselEmissionValues_particulate",
    "AdvisorySpeed",
    "ConnectingLane",
    "ConnectionManeuverAssist",
    "DataParameters",
    "IntersectionReferenceID",
    "LaneTypeAttributes",
    "Node_LLmD_64b",
    "Node_XY_20b",
    "Node_XY_22b",
    "Node_XY_24b",
    "Node_XY_26b",
    "Node_XY_28b",
    "Node_XY_32b",
    "NodeOffsetPointXY",
    "Position3D",
    "RegulatorySpeedLimit",
    "RestrictionUserType",
    "RoadSegmentReferenceID",
    "SignalControlZone",
    "TimeChangeDetails",
    "ITS_Inline_ComputedLane_offsetXaxis",
    "ITS_Inline_ComputedLane_offsetYaxis",
    "IviManagementContainer",
    "MlcPart",
    "AbsolutePosition",
    "AbsolutePositionWAltitude",
    "ComputedSegment",
    "DeltaPosition",
    "LaneCharacteristics",
    "LayoutComponent",
    "LoadType",
    "MapReference",
    "PolygonalLine",
    "RoadSurfaceDynamicCharacteristics",
    "RoadSurfaceStaticCharacteristics",
    "Segment",
    "Text",
    "VehicleCharacteristicsFixValues",
    "Zone",
    "ITS_Inline_ITS_Inline_ISO14823Code_pictogramCode_serviceCategoryCode",
    "ITS_Inline_ITS_Inline_ISO14823Code_pictogramCode_pictogramCategoryCode",
    "Ext2",
    "ReferencePosition",
    "HighFrequencyContainer",
    "LowFrequencyContainer",
    "SpecialVehicleContainer",
    "BasicContainer",
    "ManagementContainer",
    "RoadWorksContainerExtended",
    "AlacarteContainer",
    "InternationalSign_applicablePeriod",
    "InternationalSign_applicableVehicleDimensions",
    "InternationalSign_section",
    "ITS_Inline_GddStructure_pictogramCode",
    "DieselEmissionValues",
    "ComputedLane",
    "Connection",
    "LaneAttributes",
    "LaneDataAttribute",
    "MovementEvent",
    "MovementState",
    "NodeAttributeSetXY",
    "NodeXY",
    "RestrictionClassAssignment",
    "GlcPart",
    "RscPart",
    "LayoutContainer",
    "MapLocationContainer",
    "VcCode",
    "ITS_Inline_ISO14823Code_pictogramCode",
    "ITS_Inline_VehicleCharacteristicsRanges_limits",
    "Ext1",
    "CamParameters",
    "DecentralizedEnvironmentalNotificationMessage",
    "IntersectionState",
    "NodeListXY",
    "GeographicLocationContainer",
    "VehicleCharacteristicsRanges",
    "VarLengthNumber",
    "CoopAwareness",
    "SPAT",
    "GenericLane",
    "IntersectionGeometry",
    "RoadSegment",
    "TractorCharacteristics",
    "IVI_TrailerCharacteristics",
    "MapData",
    "CompleteVehicleCharacteristics",
    "LaneInformation",
    "RccPart",
    "TcPart",
    "IviContainer",
    "IviStructure",
    "GddAttribute",
    "GddStructure",
    "DestinationPlace",
    "DDD_IO",
    "InternationalSign_destinationInformation",
    "ISO14823Attribute",
    "ISO14823Code",
    "AnyCatalogue",
    "ITS_Inline_RSCode_code",
    "RSCode",
    "GicPart",
    "AutomatedVehicleRule",
    "PlatooningRule",
    "AvcPart",
    "CAM",
    "DENM",
    "IVIM",
    "SPATEM",
    "MAPEM",
]
