% Regression tests for Windows Scapy

# More informations at http://www.secdev.org/projects/UTscapy/

############
############
+ Main.py emulator

= Prepare functions

from scapy.main import *
import sys

import mock
import readline

index = 0
@mock.patch("readline.rl.readline")
def emulate_main_input(data, mock_readline):
    global index
    index = 0 # reset var
    try:
        def readline(*args, **kargs):
            global index
            if len(data) == index:
                r_data = "exit(0)"
            else:
                r_data = data[index]
            index +=1
            print r_data
            return r_data
        mock_readline.side_effect = readline
        sys.argv = ['']
        return_value = interact(returnExit=True)
        return (return_value == "0")
    except Exception as ex:
        return ex.__class__.__name__

= Test basic running
data = ["IP()", "assert _.name == 'IP'"]
emulate_main_input(data)
assert _ == True

= Test function parsing
data = ["def test():", "    return True", "", "assert test() == True"]
emulate_main_input(data)
assert _ == True
