# Readthedocs config file.

# See https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  configuration: doc/scapy/conf.py

formats:
  - epub
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  # To show the correct Scapy version, we must unshallow
  # https://docs.readthedocs.io/en/stable/build-customization.html#unshallow-git-clone
  jobs:
    post_checkout:
      - git fetch --unshallow || true

# https://docs.readthedocs.io/en/stable/config-file/v2.html#python
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
