# -*- mode: ruby -*-
# vi: set ft=ruby :

# SPDX-License-Identifier: GPL-2.0-only
# This file is part of Scapy
# See https://scapy.net/ for more information
# Copyright (C) Philippe Biondi <phil@secdev.org>

Vagrant.configure("2") do |config|

  config.vm.define "openbsd" do |bsd|
    bsd.vm.box = "generic/openbsd6"
    bsd.vm.provision "shell", path: "provision_openbsd.sh"
  end

  config.vm.define "freebsd" do |bsd|
    bsd.vm.box = "freebsd/FreeBSD-13.1-RELEASE"
    bsd.vm.provision "shell", path: "provision_freebsd.sh"
  end

  config.vm.define "netbsd" do |bsd|
    bsd.vm.box = "generic/netbsd9"
    bsd.vm.provision "shell", path: "provision_netbsd.sh"
  end

end
