% Bundle Protocol Version 7 test campaign

+ Syntax check
= Import the BPv7 layer
from scapy.contrib.bpv7 import *

+ EID CODEC

= EID encode

from scapy.cbor import *
from scapy.contrib.bpv7 import BundleEidField

class TestPkt(CBOR_Packet):
    CBOR_root = CBORF_SEQUENCE(
        BundleEidField('eid', default='dtn:none'),
    )

pkt = TestPkt()
pkt.show()
outdata = bytes(pkt)
print(outdata.hex())
assert outdata == bytes.fromhex('820100')

pkt = TestPkt(
    eid="dtn://n/s"
)
pkt.show()
outdata = bytes(pkt)
print(outdata.hex())
assert outdata == bytes.fromhex('8201652F2F6E2F73')

pkt = TestPkt(
    eid="ipn:1.2.3"
)
pkt.show()
outdata = bytes(pkt)
print(outdata.hex())
assert outdata == bytes.fromhex('820283010203')


+ Block CODEC

= Primary default
from scapy.contrib.bpv7 import *
pkt = PrimaryBlock()
pkt.show()
outdata = bytes(pkt)
print(outdata.hex())
assert outdata == bytes.fromhex('8a070000820100820100820100820000000000')

= Canonical payload encode
from scapy.contrib.bpv7 import *
pkt = CanonicalBlock(
  type_code=1,
  block_num=1,
  btsd=Raw(load=b""),
)
pkt.show()
outdata = bytes(pkt)
print(outdata.hex())
assert outdata == bytes.fromhex('850101000040')

= Canonical with CRC encode
from scapy.contrib.bpv7 import *
pkt = CanonicalBlock(
  type_code=1,
  block_num=1,
  crc_type=2,
  btsd=Raw(load=b"hi"),
)
pkt.show()
pkt.show2()
outdata = bytes(pkt)
print(outdata.hex())
assert outdata == bytes.fromhex('8601010002426869441ff585a4')

= Canonical empty decode
from scapy.contrib.bpv7 import *
pkt = CanonicalBlock(bytes.fromhex('850101000040'))
pkt.show()

= Canonical with CRC decode
from scapy.contrib.bpv7 import *
pkt = CanonicalBlock(bytes.fromhex('8601010002426869441ff585a4'))
pkt.show()
assert pkt.check_crc()


+ BPv7 CODEC

= construct default
from scapy.contrib.bpv7 import *
pkt = BundleV7()
assert pkt.primary.crc_type == 0
pkt.show()
outdata = bytes(pkt)
print(outdata.hex())
assert outdata[:1] == b'\x9f'
assert outdata[-1:] == b'\xff'

= construct only payload
from scapy.contrib.bpv7 import *
pkt = BundleV7(
  primary=PrimaryBlock(
    crc_type=2,
    destination='ipn:1.2.3',
    create_ts=BundleTimestamp(
      dtntime='2025-11-26T15:00:00Z',
      seqno=1,
    ),
    lifetime=3600000,
  ),
  blocks=[
    CanonicalBlock(
      type_code=1,
      block_num=1,
      crc_type=2,
      btsd=Raw(b'hi'),
    ),
  ]
)
pkt.show()
outdata = bytes(pkt)
print(outdata.hex())
assert outdata[:1] == b'\x9f'
assert outdata[-1:] == b'\xff'

= construct with extensions

pkt = BundleV7(
  primary=PrimaryBlock(
    crc_type=2,
    destination='ipn:1.2.3',
    create_ts=BundleTimestamp(
      dtntime='2025-11-26T15:00:00Z',
      seqno=1,
    ),
    lifetime=3600000,
  ),
  blocks=[
    CanonicalBlock(
      block_num=2,
      crc_type=2,
      btsd=PreviousNodeBlock(node='ipn:3.2.0'),
    ),
    CanonicalBlock(
      type_code=1,
      block_num=1,
      crc_type=2,
      btsd=Raw(b'hi'),
    ),
  ]
)
pkt.show()
outdata = bytes(pkt)
print(outdata.hex())
assert len(outdata) > 5
assert outdata[:1] == b'\x9f'
assert outdata[-1:] == b'\xff'
wrpcap('/tmp/foo.pcap', Ether()/IP()/UDP(sport=4556,dport=4556)/pkt)


= decoding example from Appendix A.1.1.3 of RFC 9173

from scapy.contrib.bpv7 import *
data = bytes.fromhex('9f88070000820282010282028202018202820201820018281a000f424085010100005823526561647920746f2067656e657261746520612033322d62797465207061796c6f6164ff')
pkt = BundleV7(data)
pkt.show()
assert pkt.check_crc()
assert pkt.primary.source == 'ipn:2.1'
assert pkt.primary.destination == 'ipn:1.2'

pkt.clear_cache()
outdata = bytes(pkt)
print(outdata.hex())
assert outdata == data

= decoding example from Appendix A.1.1.4 of RFC 9173

from scapy.contrib.bpv7 import *
data = bytes.fromhex('9f88070000820282010282028202018202820201820018281a000f424085070200004319012c85010100005823526561647920746f2067656e657261746520612033322d62797465207061796c6f6164ff')
pkt = BundleV7(data)
pkt.show()
assert pkt.check_crc()
assert pkt.primary.source == 'ipn:2.1'
assert pkt.primary.destination == 'ipn:1.2'

pkt.clear_cache()
outdata = bytes(pkt)
print(outdata.hex())
assert outdata == data

= decoding example from Appendix A.1.4 of RFC 9173

from scapy.contrib.bpv7 import *
data = bytes.fromhex('9f88070000820282010282028202018202820201820018281a000f4240850b0200005856810101018202820201828201078203008181820158403bdc69b3a34a2b5d3a8554368bd1e808f606219d2a10a846eae3886ae4ecc83c4ee550fdfb1cc636b904e2f1a73e303dcd4b6ccece003e95e8164dcc89a156e185010100005823526561647920746f2067656e657261746520612033322d62797465207061796c6f6164ff')
pkt = BundleV7(data)
pkt.show()
assert pkt.check_crc()
assert len(pkt.blocks) == 2
assert pkt.blocks[0].type_code == 11
#assert pkt.blocks[0].btsd.targets == [1]
#assert pkt.blocks[0].btsd.context_id == 1
#assert pkt.blocks[0].btsd.source == 'ipn:2.1'

pkt.clear_cache()
outdata = bytes(pkt)
print(outdata.hex())
assert outdata == data


= decoding example from Appendix A of draft-dtn-bpsec-cose

from scapy.contrib.bpv7 import *
data = bytes.fromhex('9f880700008201692f2f6473742f7376638201692f2f7372632f7376638201662f2f7372632f821b000000bd51281400001a000f42408501010000466568656c6c6fff')
pkt = BundleV7(data)
pkt.show()
assert pkt.check_crc()
assert pkt.primary.source == 'dtn://src/svc'
assert pkt.primary.destination == 'dtn://dst/svc'
assert len(pkt.blocks) == 1
assert pkt.blocks[0].type_code == 1

pkt.clear_cache()
outdata = bytes(pkt)
print(outdata.hex())
assert outdata == data


= decoding example from Appendix A.1 of draft-dtn-bpsec-cose

from scapy.contrib.bpv7 import *
data = bytes.fromhex(
    "9f890700028201692f2f6473742f7376638201692f2f7372632f7376638201662f2f"
    "7372632f821b000000bd51281400001a000f42404482a081c9850b03000058608101"
    "03018201662f2f7372632f818205a2000120018181821158458443a10106a1044a45"
    "78616d706c65412e31f65830ec8260a38a1a00fef2cd4aae063f50f01c5645e84c6c"
    "4893ca895eed44ef60a5f50f9adf5cc5654499b881e5896378058601010002466568"
    "656c6c6f444ec359d2ff"
)
pkt = BundleV7(data)
pkt.show()
assert pkt.check_crc()
assert pkt.primary.source == 'dtn://src/svc'
assert pkt.primary.destination == 'dtn://dst/svc'
assert len(pkt.blocks) == 2
assert pkt.blocks[0].type_code == 11
print(pkt.blocks[0].btsd.show())
assert pkt.blocks[1].type_code == 1

#pkt.clear_cache()
#outdata = bytes(pkt)
#print(outdata.hex())
#assert outdata == data


+ BPv7 User API

= bundle flags
from scapy.contrib.bpv7 import *

pkt = PrimaryBlock(
    bundle_flags="PAYLOAD_ADMIN",
)
pkt.show()
assert pkt.bundle_flags == PrimaryBlock.Flag.PAYLOAD_ADMIN

pkt = PrimaryBlock(
    bundle_flags=0x004002,
)
pkt.show()
assert pkt.bundle_flags == (
    PrimaryBlock.Flag.PAYLOAD_ADMIN | PrimaryBlock.Flag.REQ_RECEPTION_REPORT
)

pkt = PrimaryBlock(
    bundle_flags="PAYLOAD_ADMIN+REQ_RECEPTION_REPORT",
)
pkt.show()
assert pkt.bundle_flags == (
    PrimaryBlock.Flag.PAYLOAD_ADMIN | PrimaryBlock.Flag.REQ_RECEPTION_REPORT
)
