% Regression tests for Scapy

+Syntax check
= Import the homeplugg layer

from scapy.contrib.homepluggp import *
import binascii
#from scapy.all import 

# HomePlugGP

############
############
+ Basic tests

* Those test are here mainly to check nothing has been broken

= Some important parsing
~ field
_xstr = binascii.unhexlify("0108600000010000000000000000040000000227cfe35f01e50a01c8a074ad04537cb54b88b62d49b35b51000000c1f2")
pkt = HomePlugAV(_xstr)
assert pkt.NewKey == b'\xc8\xa0t\xad\x04S|\xb5K\x88\xb6-I\xb3[Q' 
assert pkt.NetworkID == b"'\xcf\xe3_\x01\xe5\n"

= Some important manipulations
~ field
pkt = HomePlugAV(version=0x01)/CM_MNBC_SOUND_IND()
pkt.RandomValue="AAAAAAAAAA"
assert bytes(pkt) == b'\x01v`\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00AAAAAAAAAA\x00\x00\x00\x00\x00\x00' 
