# SPDX-License-Identifier: GPL-2.0-only
# This file is part of Scapy
# See https://scapy.net/ for more information

"""
Package holding CBOR (Concise Binary Object Representation) related modules.
Follows the same paradigm as ASN.1 implementation.
"""

from scapy.cbor.cbor import (
    CBOR_Error,
    CBOR_Encoding_Error,
    CBOR_Decoding_Error,
    CBOR_BadTag_Decoding_Error,
    CBOR_Codecs,
    CBOR_MajorTypes,
    CBOR_Object,
    CBOR_UNSIGNED_INTEGER,
    CBOR_NEGATIVE_INTEGER,
    CBOR_BYTE_STRING,
    CBOR_TEXT_STRING,
    CBOR_ARRAY,
    CBOR_MAP,
    CBORMapData,
    CBOR_SEMANTIC_TAG,
    CBOR_SIMPLE_VALUE,
    CBOR_FALSE,
    CBOR_TRUE,
    CBOR_NULL,
    CBOR_UNDEFINED,
    CBOR_UNDEFINED_VALUE,
    CBOR_NO_ITEM,
    CBOR_FLOAT,
    CBORFloatValue,
    CBOR_DECODING_ERROR,
    RandCBORObject,
    CBORTagValue,
    CBORSimpleValue,
)

from scapy.cbor.cborcodec import (
    CBORcodec_Object,
    CBORcodec_UNSIGNED_INTEGER,
    CBORcodec_NEGATIVE_INTEGER,
    CBORcodec_BYTE_STRING,
    CBORcodec_TEXT_STRING,
    CBORcodec_ARRAY,
    CBORcodec_MAP,
    CBORcodec_SEMANTIC_TAG,
    CBORcodec_SIMPLE_AND_FLOAT,
)

from scapy.cbor.cborfields import (
    CBORBuildResult,
    CBORParseResult,
    CBORF_element,
    CBORF_field,
    CBORF_ANY,
    CBOR_ABSENT,
    CBORF_UNSIGNED_INTEGER,
    CBORF_NEGATIVE_INTEGER,
    CBORF_INTEGER,
    CBORF_BYTE_STRING,
    CBORF_TEXT_STRING,
    CBORF_BOOLEAN,
    CBORF_NULL,
    CBORF_UNDEFINED,
    CBORF_FLOAT,
    CBORF_SEQUENCE,
    CBORF_SEQUENCE_OF,
    CBORF_ARRAY,
    CBORF_ARRAY_OF,
    CBORF_ARRAY_INDEFINITE,
    CBORF_MAP,
    CBORF_SEMANTIC_TAG,
    CBORF_UNSIGNED_ENUM,
    CBORF_UNSIGNED_FLAGS,
    CBORF_optional,
    CBORF_CONDITIONAL,
    CBORF_PACKET,
    CBORF_BYTE_STRING_PACKET,
)

__all__ = [
    # Exceptions
    "CBOR_Error",
    "CBOR_Encoding_Error",
    "CBOR_Decoding_Error",
    "CBOR_BadTag_Decoding_Error",
    # Codecs
    "CBOR_Codecs",
    "CBOR_MajorTypes",
    # Objects
    "CBOR_Object",
    "CBOR_UNSIGNED_INTEGER",
    "CBOR_NEGATIVE_INTEGER",
    "CBOR_BYTE_STRING",
    "CBOR_TEXT_STRING",
    "CBOR_ARRAY",
    "CBOR_MAP",
    "CBORMapData",
    "CBOR_SEMANTIC_TAG",
    "CBOR_SIMPLE_VALUE",
    "CBOR_FALSE",
    "CBOR_TRUE",
    "CBOR_NULL",
    "CBOR_UNDEFINED",
    "CBOR_UNDEFINED_VALUE",
    "CBOR_NO_ITEM",
    "CBOR_FLOAT",
    "CBORFloatValue",
    "CBOR_DECODING_ERROR",
    "CBORTagValue",
    "CBORSimpleValue",
    # Random/Fuzzing
    "RandCBORObject",
    # Codec classes
    "CBORcodec_Object",
    "CBORcodec_UNSIGNED_INTEGER",
    "CBORcodec_NEGATIVE_INTEGER",
    "CBORcodec_BYTE_STRING",
    "CBORcodec_TEXT_STRING",
    "CBORcodec_ARRAY",
    "CBORcodec_MAP",
    "CBORcodec_SEMANTIC_TAG",
    "CBORcodec_SIMPLE_AND_FLOAT",
    # Result types
    "CBORBuildResult",
    "CBORParseResult",
    # Field base classes
    "CBORF_element",
    "CBORF_field",
    "CBORF_ANY",
    "CBOR_ABSENT",
    # Scalar fields
    "CBORF_UNSIGNED_INTEGER",
    "CBORF_NEGATIVE_INTEGER",
    "CBORF_INTEGER",
    "CBORF_BYTE_STRING",
    "CBORF_TEXT_STRING",
    "CBORF_BOOLEAN",
    "CBORF_NULL",
    "CBORF_UNDEFINED",
    "CBORF_FLOAT",
    # Structured fields
    "CBORF_SEQUENCE",
    "CBORF_SEQUENCE_OF",
    "CBORF_ARRAY",
    "CBORF_ARRAY_OF",
    "CBORF_ARRAY_INDEFINITE",
    "CBORF_MAP",
    "CBORF_SEMANTIC_TAG",
    # Complex fields
    "CBORF_UNSIGNED_ENUM",
    "CBORF_UNSIGNED_FLAGS",
    "CBORF_optional",
    "CBORF_CONDITIONAL",
    "CBORF_PACKET",
    "CBORF_BYTE_STRING_PACKET",
]
