% Regression tests for TestSocket

+ Configuration
~ conf

= Imports

from scapy.contrib.automotive.testsocket import TestSocket, cleanup_testsockets

= Create Dummy Packet

class TestPacket(Packet):
    fields_desc = [
        IntField("identifier", 0),
        StrField("data", b"")
    ]
    def answers(self, other):
        if other.__class__ != self.__class__:
            return False
        if self.identifier % 2:
            return False
        if self.identifier == (other.identifier + 1):
            return True
        return False
    def hashret(self):
        # type: () -> bytes
        return struct.pack('I', self.identifier + (self.identifier % 2))


= Create Sockets

sender = TestSocket(TestPacket)
receiver = TestSocket(TestPacket)
sender.pair(receiver)

+ Basic tests

= Simple ping pong

exception = None

def create_answer(p):
    try:
        ans = TestPacket(identifier=p.identifier + 1, data=p.data + b"_answer")
        receiver.send(ans)
    except Exception as e:
        global exception
        exception = e

t = AsyncSniffer(timeout=5, prn=create_answer, opened_socket=receiver)
t.start()

pks = PacketList()

for i in range(1, 2000, 2):
    txp = TestPacket(identifier=i, data=b"hello"*i)
    rxp = sender.sr1(txp, verbose=False, timeout=0.1)
    pks.append(txp)
    pks.append(rxp)

t.stop(join=True)
convs = pks.sr()

print(exception)
assert exception is None

assert len(t.results) == 1000
assert len(pks) == 2000
assert len(convs[0]) == 1000

= Simple ping pong with sr with packet generator

sniff(timeout=0.1, opened_socket=[sender, receiver])

conf.debug_match = True

exception = None
t = AsyncSniffer(timeout=5, prn=create_answer, opened_socket=receiver)
t.start()

txp = TestPacket(identifier=range(1, 2000, 2), data=b"test1")
rxp = sender.sr(txp, verbose=False, timeout=5)
t.stop(join=True)

print(debug.sent)
print(debug.recv)
print(debug.match)

print(rxp)
print(rxp[0].summary())
print(exception)
assert exception is None
assert len(t.results) == 1000
assert len(rxp[0]) == 1000

= Simple ping pong with sr with generated packets

sniff(timeout=0.1, opened_socket=[sender, receiver])

conf.debug_match = False

exception = None
t = AsyncSniffer(timeout=5, prn=create_answer, opened_socket=receiver)
t.start()

txp = [TestPacket(identifier=i, data=b"hello") for i in range(1, 2000, 2)]
rxp = sender.sr(txp, verbose=False, timeout=5)
t.stop(join=True)

print(rxp)
print(exception)
assert exception is None
assert len(t.results) == 1000
assert len(rxp[0]) == 1000

+ Cleanup

= Delete TestSockets

cleanup_testsockets()