.PHONY: install
install:
	cp -r utscapy/ ~/.vscode/extensions/
	@echo "The UTScapy extension will be available on the next fresh start of VS Code."

.PHONY: uninstall
uninstall:
	rm -rf ~/.vscode/extensions/utscapy/
	@echo "The extension was uninstalled, you may have to restart VS Code."
